### ISSUE TITLE
docker vhdx issue

### ISSUE THREAD

**Issue by robert-1043** [webrecorder/browsertrix-crawler#100]
Last week I ran a Heritrix crawl (on Ubuntu 18LTS), resulting in about 23GB.

This week I try to run a Browsertrix crawl of the same domain (on WSL2 Ubuntu 20LTS with 8 workers), but have problems with the Docker ext4.vhdx file on Windows.  It keeps inflating to all the available space left on the hard disk, after which the crawl hangs.  The vhdx grows to over 60GB, while the warcs of the Browsertrix crawl are about 6GB.

Is this a Docker issue or is this influenced by Browerstrix?  Solution for now is stopping the crawl (doesn't always succeed), purging WSL data in Docker, which also deletes the Browsertrix image.  I could try to relocate the vhdx, but this is a crawl of less then 4000 pages (and quite some images).  What would happen with a 40K pages crawl?

**Comment by ikreymer** [comment]
Is this still an issue currently or have you been able to find a workaround? Unfortunately, I don't have Windows to test, but this seems like a Docker and/or Windows issue. It is now possible to set a size limit and interrupt the crawl, and perhaps continue from previously interrupted crawl, if you need to limit the size..

**Comment by robert-1043** [comment]
Yes, it's still happening.  Growing size seems to be related to content (site) being crawled.  Workaround is indeed stopping the crawl, cleaning/deleting the vhdx file, starting the crawl.

Was looking if running through Podman would help, haven't been able to test it yet.

**Comment by robert-1043** [comment]
Have been using Podman on WSL2 for some time now.  There is still an issue with inflating vhdx.  Although the vhdx seems to grow less than while using Docker.

Issue seems rather to relate WSL on Windows than Browsertrix.
