### ISSUE TITLE
Are the capabilities still required?

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/browsertrix-crawler#104]
In the past, it was required to add `SYS_ADMIN` and `NET_ADMIN` capabilities to the container running it. Looking at the history, I see this was dropped off the README after 4.0b1 but to this day, it's still present in the sample docker-compose file.

In our zimit farm, we've switched it off to debug an issue and the crawls goes through. Hence the question: is it still required?

**Comment by ikreymer** [comment]
Yes, you're right, they don't seem to be required with the latest versions of Chrome, and I've also been testing without them.
I think you can remove them in zimfarm.

**Comment by rgaudin** [comment]
Thanks 👍
