### ISSUE TITLE
Support Screenshot Creation

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#11]
Add option to generate screenshots, as per:
https://github.com/webrecorder/browsertrix/blob/pywb-instance/simple-driver/index.js#L177

Store in WARC records as `urn:screenshot:<timestamp>/<url>` based on previous convention.

To decide: need options for different dimensions (eg. thumbnails?), default dimensions for screenshot?  (1024x768?)

**Comment by tw4l** [comment]
@ikreymer to review PR
