### ISSUE TITLE
Crawler stopped at CloudFlare DDOS protection challenge page

### ISSUE THREAD

**Issue by gulprun** [webrecorder/browsertrix-crawler#110]
I've tried several ways against a site(https://www.hkja.org.hk) behind Cloudflare's DDOS protection, but can't get it through. I have used all possible options(e.g.  --scopeType host --timeout 10000), however, there's no page can be fetched beyond the delaying single page provided by CloudFlare. 
![Screenshot from 2022-03-04 09-27-31](https://user-images.githubusercontent.com/33362680/156681602-7cfc7b0d-cc5b-4130-83c3-21dd1ec90b65.png)

The console output like this:
```
== Start:     2022-03-03 08:21:44.710
== Now:       2022-03-03 08:21:50.191 (running for 5.5 seconds)
== Progress:  1 / 1 (100.00%), errors: 0 (0.00%)
== Remaining: 0.0 ms (@ 0.18 pages/second)
== Sys. load: 91.3% CPU / 98.9% memory
== Workers:   1
   #0 IDLE
Waiting to ensure pending data is written to WARCs...
Generating WACZ
Validating passed pages.jsonl file
Reading and Indexing All WARCs
Writing archives...
```
_Originally posted by @gulprun in https://github.com/webrecorder/browsertrix-crawler/issues/94#issuecomment-1050473503_

**Comment by ikreymer** [comment]
This type of Cloudflare wait page should now be detected, as of 0.5.0-beta.7.
Note that it will not work if it is asking for a captcha. You can also use a browser profile to preload certain pages to avoid the captcha.
