### ISSUE TITLE
saveState: always does not always save state

### ISSUE THREAD

**Issue by KathrynN** [webrecorder/browsertrix-crawler#113]
Hi!  Great tool.
When docker / the tool crashes, there is no save state to pull from.  It would be great if every n*numberOfWorkers we could update the saved state file so that, if a crash does occur, we're not starting a 10 hour job over again (or manually copying url objects from the pages.jsonl into crawl-config.yaml )

**Comment by ikreymer** [comment]
Fixed via #124!
