### ISSUE TITLE
Unable to download non-HTML content if served with HTTP cookies

### ISSUE THREAD

**Issue by simonwiles** [webrecorder/browsertrix-crawler#129]
I'm trying to crawl a site with many PDFs that are served with HTTP cookies.  Since the introduction of https://github.com/webrecorder/browsertrix-crawler/blob/5e5efda4377c249ba0f0c9fa96659b2e28eebb49/crawler.js#L758 in ab096cd5b0fc17e841ae97ffcab64596b7b723aa, this is not possible.

`Crawler.directFetchCapture()` returns `false`, despite the fetching and recording having completed correctly and the `.warc.gz` having been written; this causes `Crawler.loadPage()` to attempt a browser-based capture, and puppeteer's `page.goto()` times out at https://github.com/webrecorder/browsertrix-crawler/blob/09082e8abb53eea2ab776ad90aa4945256d76a30/crawler.js#L310-L312

I was able to work around it by adding an additional check like this:
```js
if (await this.isHTML(data.url) && this.params.behaviorOpts) {
  await Promise.allSettled(page.frames().map(frame => evaluateWithCLI(frame, "self.__bx_behaviors.run();")));
}
```
and also passing `--wait-until domcontentloaded`, but this is obviously not ideal.

What's the logic behind checking for http cookies and forcing the use of the browser for non-HTML resources?  I've taken that restriction out in a local version to fetch the ~20k PDFs that are my immediate concern, but I don't understand everything that's going on here.

Thanks!

**Comment by simonwiles** [comment]
Quick update: I've just had to do the same to fetch other non-HTML content for another crawl (images and json, in this case).

**Comment by ikreymer** [comment]
Thanks for taking a look at this! The direct fetch logic was altered initially to deal with redirects, which were not being fetched. The cookie check was added 'just in case', as the direct fetch did not use the cookies from the browser - which is possible to do as well, in case it resulted in a 'soft 404' or not valid capture. Erring on the side of caution here, it may have introduced the unnecessary timeouts.

In simple testing, I was getting the PDF-pages to load without timeouts, Would like to take a look at the example site with PDFs to see what can be done.

**Comment by simonwiles** [comment]
Can confirm that `non-html-page-load` branch fixes the problem in the examples I have available.  Thanks!

**Comment by ikreymer** [comment]
Was fixed in earlier release!
