### ISSUE TITLE
YAML based config 

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#13]
Similar to original Browsertrix, should probably have a YAML-based config as an alternative to the command-line options
and to simplify complex configurations. Will help with #12 also.

The command-line options can take precedence.

**Comment by nvanderperren** [comment]
just a question out of curiosity: is there an idea when this will be implemented?

**Comment by kelson42** [comment]
Yaml might look nice, but it is not. Better use a strong format like json please.

**Comment by ikreymer** [comment]
@nvanderperren This is now next on our list, so hopefully will make it into 0.4.x release

@kelson42 YAML is just much easier to work with and is a common config format. Yes, it has some drawbacks.
Of course, you would be free to just use JSON as well as YAML is backwards compatible :)

**Comment by ikreymer** [comment]
Added in 0.4.0 Beta
