### ISSUE TITLE
Post-process smaller WARCs to larger WARC with warcinfo

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#14]
The crawl generates many WARCs due to several processes running in parallel.
If the final output of the crawl needs to be a WARC, there can be a 'post-processing' step to generate a single WARC:

- [x] Concatenate small WARCs to a larger WARC
- [x] Ensure concatenated WARC has a `warcinfo` record
- [x] Add max size limit (eg.  1GB), if limit exceeded, generate several WARCs upto size limit (each with warcinfo).

**Comment by ikreymer** [comment]
This has been released in 0.3.0! Max combined WARC size currently configurable with `--rolloverSize` flag.

**Comment by adityaraj-28** [comment]
Hi @ikreymer can we somehow restrict generation of only one warc file in the archive directory for a url, considering we are using scope type as `page` or `page-spa`
