### ISSUE TITLE
No image for 0.7.0-beta.2

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/browsertrix-crawler#148]
Although a beta.2 has been committed about 9d ago, [Docker hub](https://hub.docker.com/r/webrecorder/browsertrix-crawler/tags) still only references beta.1.

I am wrong in assuming that all those intermediate releases would be pushed to the registry? Was is simply forgotten?

**Comment by ikreymer** [comment]
It is still in development, wanted to do more testing, but you can test the main branch for now.

**Comment by rgaudin** [comment]
OK ; I'm happy with only testing (inside `zimit:dev`) what you consider safe-enough for pushing it yourself. I wasn't sure it it had been forgotten or not.
