### ISSUE TITLE
[Feature request] Prioritize entries in queue (by regex?)

### ISSUE THREAD

**Issue by bjrne** [webrecorder/browsertrix-crawler#150]
As an archiver, I want to make sure that the most important subpages from a domain are crawled as soon as possible in long-running crawls to prevent data loss. There are crawls where I want to enable the extraHops setting and also download more pages from the same domain, but some are inherently more important. In a crawl that runs for days, prioritizing these urls can be important, because it would enable users to stop the crawl at some point and being reasonably sure to have the main pages.

My idea would be to define regex rules for Prio 1, 2 & 3, similar to include and exclude rules. A url then gets the priority rating of the highest matching regex and the queue is periodically sorted by that (or a PriorityQueue by nature). Another easier possibility could be to defer crawling extraHops to the end, to make sure to first have all main pages.

What do you think? Is this something interesting? With some hints, I could try to start working on it.

**Comment by wsdookadr** [comment]
Some thoughts on this:

It would also be nice to have an endpoint like `/update-config` so the user can update the crawler's YAML config based on observations of the partial data crawled up to that point. The main use-cases would be reprioritization like @bjrne writes, or new block/exclude rules. 

This would allow the user to have more control over the crawling process.

The change from [FIFO queue](https://github.com/webrecorder/browsertrix-crawler/blob/cf90304fa736bef1443f35a943a1700491e1e8ad/util/state.js#L70) that keeps track of the urls crawled would need to be replaced with a [priority queue](https://en.wikipedia.org/wiki/Priority_queue).

**Comment by ikreymer** [comment]
@bjrne do you have some examples of how this would be used, how many priorities levels would you want? three levels, high, med, low, or more? This could probably be done with just having multiple queues for both in-memory and redis state (using https://redis.io/commands/lmpop/)


@wsdookadr updating the config dynamically would be a separate feature, there's actually what webrecorder/browsertrix-crawler#111 is about.

**Comment by bjrne** [comment]
As an example, let's say I have a blog i want to archive. Let's say its structure is broadly this:
```
blog.com/article
blog.com/author_profile
external.com/linked_media_from_article_page
external.com/inked_page_from_author_profile
```

I mostly want to archive blog articles (i.e. same domain with include rule), but it would be nice to also include 1 extraHop (for the external pages). However, at the time of starting the crawl, I have no idea how big the crawl gets. Currently, if some author profile linked on the first article has lots of outgoing "extraHops" links, it might take ages until the next blog article is crawled. However, I still don't want to discard/exclude/ignore these external links, since I might want to archive them later as well.

Another argument why I don't want to crawl extraHops immediately is that I have no idea and control over how crawlable and big those external pages are. I know the blog is well structured, but I can't say the same about external pages. So they can hold up the crawl for longer than it would take to archive the whole blog itself.

* Idea 1: at least postpone the extraHops urls to the end of the crawl (due to unknown structure)
* Idea 2: have a `PrioHigh` regex (like `/article` in this case) that makes sure that any links matching this regex are crawled before other links, i.e. blogposts before author and external pages in this example

I'm not settled on the number of priority levels, I think any number (even PRIO/NON-PRIO) would be better than nothing, but IO think your suggestion with high, medium, low should cover most usecases. Low could be used for extraHops by default, and then the user can still have one extra level of priority.

@ikreymer  Is it more clear now?

**Comment by ikreymer** [comment]
Considering another option that I think will be even more flexible. Using the Redis sorted set, we can actually queue things based on the crawl depth, so pages can be automatically sorted based on depth from the seed. Extra hops could always be placed at the end, eg. with a very high depth score.

**Comment by bjrne** [comment]
I'll test it as soon as I can! Sounds awesome, will probably be enough for most of my use-cases, since with clever starting points, I think you could even emulate rules like "crawl everything under /blog first" if you give the /blog url as the starting point. Because then the more important pages will have minimum depth and the rest will automatically be crawled later. 

However, for some use-cases, having a regex rule to up the priority even more could still be interesting, especially since the implementation seems more easy now, I'll see.
