### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by dan83g** [webrecorder/browsertrix-crawler#151]
Is it possible to use sitemap file?
And what is the format of the sitemap file.
Thank you.

**Comment by dan83g** [comment]
I use --useSitemap and 
serving sitemap.xml via nginx on localhost. It worked.

**Comment by ikreymer** [comment]
> The original site does not have a sitemap.xml. I created sitemap.xml via https://www.xml-sitemaps.com/ and added extralinks from dynamic menu. Then used --useSitemap and served sitemap.xml via nginx on localhost. It worked.

Glad that this worked! Closing, feel free to open new issue if there are further issues.
