### ISSUE TITLE
Performance comparison to IA's brozzler?

### ISSUE THREAD

**Issue by goelayu** [webrecorder/browsertrix-crawler#152]
Do we have any understanding of how browsertix-crawler compares to [Brozzler](https://github.com/internetarchive/brozzler) with respect to crawling throughput performance, CPU, disk, NW usage etc? 
Also, any features unique to this repo that argue for having two different browser based archival crawlers?

**Comment by ikreymer** [comment]
Hi @goelayu, this is a broad question, 'performance' can mean many different things, including accuracy of capture / replay, cpu/mem requirements, as well as total running time.

The goals of this tool are many, including at its simplest, a single-command that runs a container and produces a crawl when the command exits. A key focus is on archiving fidelity, including archiving complex content, such as complex videos such that they replay in page, and providing some level of automation. Additionally, browsertrix crawler is fully customizable with Puppeteer scripts, which can be added to customize the operation of the crawl.
Browsertrix Crawler is designed to be a component in the Browsertrix Cloud systems, which will have a UI, API and crawl management system. Some of the [features planned for Browsertrix Cloud](https://browsertrix.cloud/features/) are actually also part of Browsertrix Crawler.

The complexity of web archiving makes benchmarking tricky, and not something we have time for at the moment.

One effort that is doing something close to benchmarking is the Game Walkthroughs project by Travis Reid, described here: https://netpreserve.org/projects/game-walkthroughs/
Some recent results mentioned here: https://twitter.com/TReid803/status/1549819244975734786

**Comment by ikreymer** [comment]
Closing for now, feel free to open if there's additional questions.

**Comment by robert-1043** [comment]
I had the impression Brozzler was abandoned by IA? 

Have tested it July 2018, found it quite difficult to get it working (dependencies, rethingDB, documentation).  But for most: it didn't do what it was said to be capable of: it didn't archive some of our more dynamic web projects.  Browsertix 2021 did, haven't tried Brozzler in 2021/2022.

**Comment by avdempsey** [comment]
Brozzler is in heavy use and under active development at IA. I expect that to continue for years to come. Much of the recent work has focussed on our internal use cases. It could absolutely use some love to make it easy to run out of the box, and we'll forever be chasing capture fidelity with the evolving web.
