### ISSUE TITLE
Integrate adblock list directly

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#154]
It's probably time to add some sort of default ad-blocking would great enhance performance for many sites, and probably something that should be added to base image. There's a few options, one is:

1) /etc/hosts blocking using an existing block list, to prevent the URLs from loading. This is what zimit already does, eg: https://github.com/openzim/zimit/blob/master/Dockerfile#L15

2) blocking at the request interception level. This could be downloading a list of hosts to block, converting to JSON, and loading the json file on load and simply abort any requests to the specified domain. This is what browserless/chrome does, eg: https://github.com/browserless/chrome/blob/master/scripts/postinstall.js#L96

It seems that there's a few host blocking lists out there, including the ones used by zimit and browserless/chrome.

@rgaudin do you have any feedback on how the adblocking has been working out with zimit at the /etc/hosts level? I imagine the lists you're using sufficient for your needs?

**Comment by ikreymer** [comment]
This would replace the need to manually install an adblock extension, as was suggested in #119, which would be more cumbersome. Thinking of perhaps including a default list of hosts which will be baked into the image, with option to specify a custom list, should anyone need that..

**Comment by caj-larsson** [comment]
If we do #103 we have the option of delegating adblocking by [using the launch flag](https://docs.browserless.io/docs/chrome-flags.html#blocking-ads)

**Comment by rgaudin** [comment]
> @rgaudin do you have any feedback on how the adblocking has been working out with zimit at the /etc/hosts level? I imagine the lists you're using sufficient for your needs?

It's pretty great as a no brainer default ad-blocking. We've had one request to extend it though ; not to an ad domain but to multi-purpose domain like googleapis.com. For such cases, I suppose only extensions would be reliable.

We actually were wondering how those host-redirected requests are handled. Is there a WARC record type for those that registers the request and the connection error or is it not reflected at all in the WARC? In such case, how would the replayer know not to connect to the online version?
