### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by wenjin11** [webrecorder/browsertrix-crawler#159]
requests.exceptions.SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /publicsuffix/list/master/public_suffix_list.dat (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

**Comment by rgaudin** [comment]
Looks like this belongs to zimit

**Comment by kelson42** [comment]
@rgaudin Should we close this ticket (seems related to the setup, not to the data and we anyway have no way to reproduce it)? Or move it to `openzim/zimit`?

**Comment by rgaudin** [comment]
We can't close tickets here ; that's why it's still there…
