### ISSUE TITLE
Add Crawl Depth Option

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#16]
To support #12, will also need to add a crawlDepth option to support crawling to various depths, eg. one-hop-out

**Comment by aleksandrmelnikov** [comment]
Hey there! Would it be okay if I try to implement this?

**Comment by ikreymer** [comment]
Hi @aleksandrmelnikov , sure that would be great!

What we were thinking was a `--crawlDepth` option, and then each URL has an associated depth, eg:
`this.cluster.queue({url, depth});`

Then, `extractLinks` is called if depth < crawlDepth.

Or, perhaps start at the crawlDepth and count down and check if `depth > 0`, tis may be more flexible, to allow different seed URLs at different depths.

Is this sort of what you were thinking also?

**Comment by aleksandrmelnikov** [comment]
Thanks! Love this project and webrecorder in general :).

I'm partially leaning towards the depth < crawlDepth.

But I need to dig into the code a bit more and get a feel for how it executes.
I'll definitely post back with some feedback.

A side thought: What about depth and links that point outside of the domain (of the url)?
- Say example.com makes a network resource request to "badexample.com"?
Is depth related to this portion at all?

**Comment by ikreymer** [comment]
> 
> * Say example.com makes a network resource request to "badexample.com"?
>   Is depth related to this portion at all?

We already have the `--scope` setting for this, which accepts a regexes that match what is 'in scope' for the crawl.
There's also a new simplified `--scopeType` which will configure the regexs automatically in a common way (just current page, current page prefix, current domain, etc...)

The system is already set up to reject URLs that are not in scope, so I think the depth will pretty much just be to determine if we call `extractLinks` again or not.

**Comment by aleksandrmelnikov** [comment]
Sorry for the silence on this, got pulled away by real life. Still on this issue.

**Comment by ikreymer** [comment]
I'm in the process of refactoring scope and multi-seed support, needing to implement this as part of that work, so it'll likely make it as part of that update.

**Comment by ikreymer** [comment]
Added as part of 0.4.0 Beta 1
