### ISSUE TITLE
Crawler doesn't download lazy loaded images

### ISSUE THREAD

**Issue by Liz-chan** [webrecorder/browsertrix-crawler#165]
I'm trying to use the crawler on this site, and it seems to get images up to a point and then doesn't anymore. Since the images are lazy-loaded, this prevents you from being able to archive the page correctly. I've tried using the autoscroll and autofetch behaviors and they don't help with it either, so I'm not sure if I'm just doing something wrong, or if it's a bug with the crawler.

The site is https://scottaohara.github.io/tests/html-img/lazy-img-links.html

**Comment by ikreymer** [comment]
Thanks for reporting! Yes, this is a bug, will be fixed in the next beta release.
The autofetch behavior was not detecting `<img loading='lazy'>` and forcing them to be eagerly loaded, which is fixed in 0.3.4 of behaviors.

**Comment by ikreymer** [comment]
The fix is part of the 0.7.0-beta.5 release. Let us know if there are any additional issues with this.

**Comment by Liz-chan** [comment]
Thanks, seems to work great now. 

An unrelated question, do you think Webrecorder would be able to open a .wacz file if it was more than 1TB?
