### ISSUE TITLE
Autoscroll default: docs differ from args

### ISSUE THREAD

**Issue by leppert** [webrecorder/browsertrix-crawler#169]
The docs say autoscroll is disabled by default. The argParser includes it by default. I'd submit a PR but I'm not sure which is preferred.

https://github.com/webrecorder/browsertrix-crawler/blob/main/README.md?plain=1#L424

https://github.com/webrecorder/browsertrix-crawler/blob/314ee3f730875dfc2bf7bed3a2c4acbbb11dfe47/util/argParser.js#L204

**Comment by ikreymer** [comment]
Thanks for finding this! Yes, this was just changed in the latest beta, it should be enabled now by default now, made i a bit 'smarter' now (only scrolls when needed)
