### ISSUE TITLE
Run crawl as current user instead of as root

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#170]
Currently, the crawler runs as root when running in Docker (though other container runtimes, like podman, use the current user).

Perhaps should look into instead creating a user based on the uid/gid of the `crawls` directory, and creating a user automatically,
very similar to what we have in:
https://github.com/webrecorder/pywb/blob/main/docker-entrypoint.sh

**Comment by edsu** [comment]
I've updated the PR to change the default directory that `create-login-profile.js` uses to `/crawls/profiles/` to simplify the permissions issue introduced by this change. If the directory doesn't exist it will create it.

I've also updated the docs to reflect the change, and noticed a small bug in the command line argument ordering for the profile extension example (I think that `--profile` needs to appear after `create-login-profile`).

It's possible that this could impact code that is using browsertrix-crawler, like browsertrix-cloud maybe?
