### ISSUE TITLE
Issues when running using Rancher desktop

### ISSUE THREAD

**Issue by GeetsM** [webrecorder/browsertrix-crawler#174]
When running the current version 0.7.0 with Rancher Desktop, I get the following exception. Any way to fix this?
`groupadd: GID '20' already exists`
`groupmod: group 'archivist' does not exist`

For 0.6.0 this does not happen. My Rancher desktop uses docker://20.10.18 as container runtime.

**Comment by edsu** [comment]
@GeetsM I installed Rancher (AppleOS) but it wasn't immediately clear to me how to run browsertrix-crawler using it. I did make some changes to the `docker-endpoint.sh` to hopefully guard against the Group ID already existing. Would you be willing to test it out using this Docker image?

    edsu/browsertrix-crawler:t174

**Comment by GeetsM** [comment]
I tried running it like this but then I get the following:

`docker run --rm -v $PWD/crawls:/crawls/  edsu/browsertrix-crawler:t174 crawl  --url <test url> --limit 1 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Set netIdleWait to 2 seconds
Storing state in memory
Crawl failed
Error: Unable to launch browser, error message: Failed to launch the browser process!
[169:169:1024/065826.275342:ERROR:nacl_fork_delegate_linux.cc(311)] Bad NaCl helper startup ack (0 bytes)
[137:200:1024/065838.013131:ERROR:file_path_watcher_linux.cc(321)] inotify_init() failed: Function not implemented (38)
[1024/065838.172627:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)
== Workers:   0

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at Cluster.init (/app/node_modules/puppeteer-cluster/dist/Cluster.js:110:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.launch (/app/node_modules/puppeteer-cluster/dist/Cluster.js:69:9)
    at async Crawler.crawl (/app/crawler.js:552:20)
    at async Crawler.run (/app/crawler.js:304:7)
failed
`

**Comment by edsu** [comment]
My apologies, I didn't do a multi-platform build for that image. Can you give it another try?

**Comment by GeetsM** [comment]
@edsu 
I just retested and it is working now.

`Set netIdleWait to 2 seconds
Storing state in memory
Text Extraction: Disabled
note: waitForNetworkIdle timed out, ignoring

== Start:     2022-10-27 07:56:44.662
== Now:       2022-10-27 07:57:03.598 (running for 18.9 seconds)
== Progress:  1 / 1 (100.00%), errors: 0 (0.00%)
== Remaining: 0.0 ms (@ 0.05 pages/second)
== Sys. load: 6.4% CPU / 46.0% memory
== Workers:   1
   #0 IDLE 
Waiting to ensure pending data is written to WARCs...
done
`

**Comment by igor-martynov** [comment]
I have almost the same issue running docker container on Debian 11

docker -D run -v /path/to/dir/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --help
groupadd: GID '5' already exists
groupmod: group 'archivist' does not exist
DEBU[0002] [hijack] End of stdout

and of course group with such low GID already exist. maybe much greater GID like 1100 or 60000 should be used?..

**Comment by ikreymer** [comment]
@igor-martynov does the fix in the branch / PR listed above work for you?

**Comment by edsu** [comment]
Just in case it wasn't clear @igor-martynov the temporary fix is to try using `edsu/browsertrix-crawler:t174` instead of `webrecorder/browsertrix-crawler` when running browsertrix-crawler. This is a temporary fix until the change is released.

**Comment by igor-martynov** [comment]
That did help, thank you very much. And thanks for explanation.
