### ISSUE TITLE
docker build error (Node incompatability with warcio.js)

### ISSUE THREAD

**Issue by edsu** [webrecorder/browsertrix-crawler#175]
When I run `docker build` on main 1213694dde690e904d1b244ac61c83d4277aac2f I'm seeing an `npm install` error:

```
#11 12.59 [2/4] Fetching packages...
#11 25.28 error warcio@1.6.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.15.1"
#11 25.29 error Found incompatible module.
```

It appears that warcio.js now [requires](https://github.com/webrecorder/warcio.js/blob/main/package.json#L27) Node v18?

**Comment by edsu** [comment]
It looks like browsertrix-crawler's Dockerfile needs to be updated to use the latest [browsertrix-browser-base](https://github.com/webrecorder/browsertrix-browser-base)?

**Comment by edsu** [comment]
Updating to latest browsertrix-browser-base works for the `docker build`, but the `require warcio` no longer works when running a crawl:

```
/app/crawler.js:25
const warcio = require("warcio");
               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/warcio/index.js from /app/crawler.js not supported.
Instead change the require of index.js in /app/crawler.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/app/crawler.js:25:16)
    at Object.<anonymous> (/app/main.js:59:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.11.0
```

**Comment by edsu** [comment]
It looks like the problem here is that `warcio.js` was [switched recently](https://github.com/webrecorder/warcio.js/commit/4f6686335d49aef09c4df29e232d226673c29297) to be an ESM module.

**Comment by ikreymer** [comment]
Yes, just switched it recently, for now should update to you the 1.5.x warcio, until we upgrade browsertrix-crawler to use esm as well.
