### ISSUE TITLE
Upgrade to use ESM

### ISSUE THREAD

**Issue by edsu** [webrecorder/browsertrix-crawler#177]
Since the latest warcio.js uses ESM we will need to update browsertrix-crawler to a module in order to use it. For the moment warcio.is is pinned to < v1.6.0.  Once the imports have been fixed we can continue to install the latest/greatest warcio.js

**Comment by edsu** [comment]
I think this is mostly done, but warcio is still pinned to v1.5.1

**Comment by ikreymer** [comment]
Implemented on the dev/0.8.0 branch

**Comment by tw4l** [comment]
Fixed in https://github.com/webrecorder/browsertrix-crawler/commit/277314f2dea064c5e4f1daee9ed29950d6707808
