### ISSUE TITLE
Investigate automatic blocking of cookie popups

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#182]
Brave recently added a feature for blocking cookie popups, I believe it is using: https://easylist.to/ cookie list.
If this works well enough as a Brave feature for users, we should definitely look into adding this as an option for the crawler!
I assume this could work similarly to the ad block, where we download the list and then apply it as part of the request handling to add cookies?

**Comment by tw4l** [comment]
The question is whether to implement in the browsertrix-crawler code via #187 or to switch to using Brave in the crawler with a custom profile, which would net the same result and possibly have other benefits as well.

**Comment by tw4l** [comment]
Related to https://github.com/webrecorder/browsertrix-crawler/issues/189

**Comment by tw4l** [comment]
Now that we're using Brave, this is doable via a browser profile using Brave's build-in features, so closing!
