### ISSUE TITLE
Consider switching to Brave for base browser.

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#189]
The actually change would be made via https://github.com/webrecorder/browsertrix-browser-base, but probably should discuss here.

Main benefit would be the ability to enable adblock + cookie popup blocking out-of-the-box via the features provided by Brave, instead of having to maintain them separately, as per #152 and #182. Some trade-offs:

Pros:
 - Less surface area to maintain, can use the state-of-the-art ad + cookie blocking provided by Brave.
 - Potentially simpler release cycle for base browser image, can just use the built binaries for amd and arm from GitHub, rather than Chrome for amd64, and Chromium for arm64
 - Potential enhancements to crawl data, using Brave-specific features, like https://github.com/brave/brave-browser/wiki/PageGraph
 
 Cons:
 - Mostly already implemented adblocking + cookie popup blocking
 - Brave doesn't provide a command-line option to enable ad + cookie blocking, would need to use a profile, instead of a command-line option.
 
Currently leaning towards making the switch.

**Comment by ikreymer** [comment]
Thinking of switching to Brave for next version to make it easier to simplify keeping up-to-date with latest browsers.
Unfortunately, Canonical is no longer releasing Ubuntu .deb for Chromium, and there is no Linux Chrome for ARM64,
so this is our best option to release both ARM64 and AMD64 images.
Brave has ARM64 and AMD64 release published to GH.
Let us know if you this is will pose issues for your use cases (we may be able to support both Brave and Chrome for AMD64)

**Comment by Shrinks99** [comment]
Considering closing this issue because we did this and it's complete!
