### ISSUE TITLE
profile creation

### ISSUE THREAD

**Issue by robert-1043** [webrecorder/browsertrix-crawler#218]
with latest version
the embedded browser isn't generated in the iframe at http://localhost:9223/

source code says
```
<div id="screen">
        <!-- This is where the remote screen will appear -->
</div>
```

(Chrome/Edge/Firefox on Windows 10)

**Comment by ikreymer** [comment]
Do you have the correct ports exposed, including 6080 ? eg:
```
docker run -p 6080:6080 -p 9223:9223 -v $PWD/crawls/profiles:/crawls/profiles/ -it webrecorder/browsertrix-crawler create-login-profile --url "https://example.com/"
```

**Comment by robert-1043** [comment]
Thanks, I copy/pasted older code from my notes which contains port 9222

(should have read the updates in the manual)
