### ISSUE TITLE
Per-Crawler Instance status messages

### ISSUE THREAD

**Issue by Shrinks99** [webrecorder/browsertrix-crawler#228]
As part of the new watch crawl page we want to give users a better indication of what each browser window is doing.  Browsertrix-crawler needs a set of defined states we can pull from to show users what each instance is working on.

### Status Messages
- Starting Crawler (This is probably more accurately a browsertrix-cloud status message relating to starting the worker but I'm including it here anyways)
- Loading Page
- Scrolling Page
- Running Behavior (??)
- Fetching Video (To be used when loading a video specifically after a page has been captured)
- Idle (Also probably more of a browsertrix-cloud thing, to be shown once a crawl is in the final stages of being completed and there are no more URLs in the queue but other workers are still doing things)

**Comment by ikreymer** [comment]
Currently, the possible granularity per browser could be:
- waiting for page (if waiting for first page, less pages than crawlers)
- loading page (waiting for page to finish loading)
- running behavior (this includes scrolling, as well as site-specific behaviors and playing videos)

Crawler-wide states:
- initializing (waiting for redis, etc..)
- waiting for remaining requests (all pages done, backend still finishing)
- creating WACZ 
- uploading WACZ
- waiting for other crawlers to finish (if scale > 1 and one finished, while others did not yet)

Will need to think about where we can store these states in a better way.
Might be possible to get more granular info on behaviors (top-level behaviors vs embedded video waiting)

**Comment by ikreymer** [comment]
Currently implemented with on per-crawler level using `<id>:status` key in redis:
- pending-wait -- waiting for requests to finish
- generate-wacz -- waiting for wacz generation
- uploading-wacz -- waiting for wacz upload

Waiting for redis can't be tracked in a redis key of course. Waiting for other crawlers to finish is handled by checking the individual crawler states (eg. if one is not 'finished', then state is not finished). Browsertrix Cloud operator checks for these per-instance states and if redis is available or not.
Additional work on this would be in Browsertrix Cloud, so closing this issue for now.
