### ISSUE TITLE
Disable browser updates

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/browsertrix-crawler#246]
We've noticed that should a run last long enough (at least consistent in 15mn ones), WARC includes data that we did not request: the google chrome update files.

Apparently, the browser phones home, realizes it's not up to date and automatically downloads update data… all of this happening inside the proxied environment.

In zimit, we chose to disable updates for now.

See https://github.com/openzim/zimit/issues/172

**Comment by ikreymer** [comment]
@rgaudin Thanks for sharing! Yes, we definitely want to disable this. For reference, where did you find the way to do this?
I see Chromium has a bunch of flags related to auto-update as well..

We are actually considering switching to Brave for crawling, which should not have the same issue.

**Comment by kelson42** [comment]
https://github.com/openzim/zimit/commit/6324b7c7c521c76e4e12e03b2fa01a44b10234c5

**Comment by ikreymer** [comment]
No longer an issue in 1.x, now switched to Brave, and no longer recording all traffic from browser, only from certain windows.
Can revisit if other issues arise - I think Brave does download some updates while running that may/may not be possible to disable (can discuss more in #463)
