### ISSUE TITLE
Attribute name parameter for crawler.extractLinks

### ISSUE THREAD

**Issue by karenhanson** [webrecorder/browsertrix-crawler#25]
Having access to the `crawler.extractLinks` function within the overridable `defaultDriver.js` is very helpful for controlling the scope of the crawl. At the moment, though, it will only work if your selector is for tags with href attributes (see `elem.href`): 
https://github.com/webrecorder/browsertrix-crawler/blob/7cfeefd19bae1bd2390286f66ffcaf1096a01985/crawler.js#L480
Converting the function to include an optional attribute property would make this more powerful: 
`extractLinks (selector = 'a[href]', attribute= 'href')` 
For example, the selector might be `figure[data-url]` and the attribute either `data-url` if using `getAttribute()`, or `dataset.url` if appending to `elem`.

**Comment by ikreymer** [comment]
That makes sense. Or can include an array of attributes.
I wonder if the default should change, but definitely easy enough to support to make it available in a custom driver.

**Comment by ikreymer** [comment]
Fixed in 0.4.1!
Now can specify `crawler.extractLinks("figure[data-url]", "data-url", true)` to load `elem.getAttribute("data-url")` from each matched element.
See: https://github.com/webrecorder/browsertrix-crawler/blob/main/crawler.js#L431
