### ISSUE TITLE
Error puppeteer: Unable to get browser page

### ISSUE THREAD

**Issue by PedroG1515** [webrecorder/browsertrix-crawler#262]
Error puppeteer: Unable to get browser page

![image](https://user-images.githubusercontent.com/25795364/227228114-b7e35649-b7ab-4b25-803e-618e46502fdd.png)

It is hard to figure out what was the problem that resulted in the error.

**Comment by ikreymer** [comment]
This logging is from a fairly older (<0.8.0) version. The logging has been much improved in 0.8.0 and 0.9.0.
Please try the latest (0.9.0 beta image being built now).

**Comment by ikreymer** [comment]
Just pushed the `webrecorder/browsertrix-crawler:0.9.0-beta.1` which should have much better logging.
Closing this for now, since the log format is too different from the error, and we've also switched to Playwright from puppeteer, so won't see that error anymore.
