### ISSUE TITLE
Network error when using --config and config file

### ISSUE THREAD

**Issue by darcyparksliu** [webrecorder/browsertrix-crawler#269]
I ran into a strange problem when runing `browsertrix-crawler` with the `--config` argument. It works when I use `stdin`, but not when I use a config file. I am using podman on RHEL8.

I had been using the `--seedFile` argument, which worked fine, but I switched to `--config` so that I could specify `depth` and `scopeType`.

For the sake of testing, I created a config.yaml with only two lines:
```
seeds:
  - url: https://github.com/webrecorder/browsertrix-crawler
```

Here is the command I tried:
```
podman run -i -v /path/to/config.yaml:/app/config.yaml -v /path/to/crawls:/crawls/ webrecorder/browsertrix-crawler:0.8.1 crawl  --generateCDX --config /app/config.yaml --collection test_2023-03-30 --depth 0
```

Here is the error that shows up
```
{"logLevel":"error","timestamp":"2023-03-30T07:52:08.454Z","context":"general","message":"Page Load Error","details":{"msg":"net::ERR_TUNNEL_CONNECTION_FAILED at https://github.com/webrecorder/browsertrix-crawler","page":"https://github.com/webrecorder/browsertrix-crawler"}}
```

The strange thing is that it works fine when I use `--config stdin`.

This command works:
```
cat /path/to/config.yaml | podman run -i -v /path/to/crawls:/crawls/ webrecorder/browsertrix-crawler:0.8.1 crawl  --generateCDX --config stdin --collection test_2023-03-30 --depth 0
```

And it works fine if I use --seedFile and a .txt with a list of URLs:
```
podman run -i -v /path/to/urls.txt:/app/config.txt -v /path/to/crawls:/crawls/ webrecorder/browsertrix-crawler:0.8.1 crawl  --generateCDX --seedFile /app/config.txt --collection test_2023-03-30 --depth 0
```

The problem came while using browsertrix-crawler 0.8.1 but I tested and have the same problem with 0.7.0.

**Comment by ikreymer** [comment]
Hm, the `net::ERR_TUNNEL_CONNECTION_FAILED` indicates a connection error from the browser. I wasn't able to repro this. I guess you can try updating to the latest, though it seems like that shouldn't make a difference here.
Also try changing the path of the config.yaml, or, perhaps its some sort of firewall issue as well.

**Comment by darcyparksliu** [comment]
Aha! The error persisted with 0.9.1 and 0.10.0-beta.0, but then I tried changing the path of config.yaml to crawl-config.yaml (which is suggested in the Readme, now that I read it again). Now it works.

I see that /app/config.yaml is mentioned in uwsgi.ini, so I guess it should hold some other data than what I had in it.
