### ISSUE TITLE
Crawler doesn't mark invalid URL as failed

### ISSUE THREAD

**Issue by tw4l** [webrecorder/browsertrix-crawler#286]
If the crawler is given an invalid URL such as `https://doesntexist.webrecorder.net`, rather than having a failed URL as one would expect, instead the page loads and runs behaviors, is marked as succesfully done, and has a load state of 4 (`BEHAVIORS_DONE`) in the resulting `pages.jsonl`.

**Comment by rgaudin** [comment]
See #207 as well
