### ISSUE TITLE
Introduce new Limit Parameter crawl-size

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#290]
I am currently using Browsertrix with all Limit Parameters (size, page, time) but for enhanced planing of parallel crawls it would be very beneficial to have another parameter to limit the size of one single crawls!
My Setup is to start Browsertrix via bash script triggered by chron
This means, that always the same command and collection with the same limits is called
As sizeLimit is taking the entire Crawl Folder to determinate if the limit is hit, it will always hit in the following crawls again and Browsertrix will only crawl one page and stop because of the sizeLimit ( works as designed)
In my scenario I want to configurate the Limit for one execution, so the only thing to cahnge would be to remember the size of the colection in the beginning and compare it in every iteration.
So one quick example:
MyCollection with the name media_daily has alredy 55 GB 
The configurated sizeLimit is lets say 100GB 
I want the crawler to force to end the crawl after max 5 GB 
I can't; I can only assume how many GB will be written in let's say one hour and limit it by time because otherwise it would crawl until the sizeLimit 100 GB (if no page limit is set) and will hardly crawl anything (Only the given main Seed) on the next days if no manual correction has been made
The Workflow of crawl-size with the example one time more:
Start: Read Collection size (55 GB) and remember (don't know eq:  INIT_COLLECTION_SIZE)
Calculate the limit via  LIMIT_CRAWL_SIZE = INIT_COLLECTION_SIZE + crawl-size (5GB) = 60 GB
Check in the same loop for the other limits if LIMIT_CRAWL_SIZE is hit

**Comment by ikreymer** [comment]
Is there a reason that a new collection per crawl doesn't work? You could just pick a new collection name your bash script, like `media-daily-{YYYY-MM-DD}` or something like that? That would make it easy to track each day's crawl, you could use --sizeLimit and you could still merge the data later by moving all the WARCs into one collection.

**Comment by gitreich** [comment]
You are rightm, as i am starting browsertrix with an own bash script it would be easy manageable to add a date suffix for the daily media collections, and it could also be easily re organised in a post processing. 
But the reason, why I am still asking to add the parameter, is that I use different configs for starting browsertrix but writing in the same collection name. This was my approach for event_crawls to get them all together in one Folder, even when the crawled pages differ very much. For my event crawl (small elections) i had also huge exclusion lists, to get only the content of intrest of divers web sources so i am ending up writing configs for every seed, so from my point of view it would still be reasonable to have control over the crawl size limit independendly of which collection i am using, as it keeps the folders organised (and you know the exact size of every collection) and without an obligated post processing
I can surley rethink my aproach but it has defenetly some benfits to have a slim and easily overlooked file structure in the collection folder of browsertrix

**Comment by ikreymer** [comment]
We don't currently track the size of the individual files, but the size of the directory itself, so it would still be a limited on the directory size.

> Start: Read Collection size (55 GB) and remember (don't know eq: INIT_COLLECTION_SIZE)
Calculate the limit via LIMIT_CRAWL_SIZE = INIT_COLLECTION_SIZE + crawl-size (5GB) = 60 GB
Check in the same loop for the other limits if LIMIT_CRAWL_SIZE is hit

You can actually do that in your shell script with something like:
```
INITIAL_SIZE=${du /path/to/collection}
docker run browsertrix-crawler crawl ... --sizeLimit ${INITIAL_SIZE + LIMIT_CRAWL_SIZE}
```
