### ISSUE TITLE
Allow spaces in userAgentSuffix command line option

### ISSUE THREAD

**Issue by anjackson** [webrecorder/browsertrix-crawler#293]
I'm attempting to set a custom User Agent using the `--userAgentSuffix` command. I want the suffix to be:

    --userAgentSuffix "bl.uk_ldfc_bot/bc (+ http://www.bl.uk/aboutus/legaldeposit/websites/websites/faqswebmaster/index.html)"

But when I try it, the suffix ends up as:

    "bl.uk_ldfc_bot/bc 

Is there a way to avoid this happening?

**Comment by tw4l** [comment]
@anjackson I believe that this has been recently fixed in https://github.com/webrecorder/browsertrix-crawler/commit/b303af02efa976a42b8df12ba1e68fd86c7f04f3 - essentially the Docker entrypoint script was breaking all the arguments on spaces, since the quotes were being stripped out by the shell before that point.

Can you try again with browsertrix crawler 0.9.0 and see if you still have the same issue?

**Comment by tw4l** [comment]
Adding a log line for the user agent to the crawler on latest `main` and using this command:

```
docker compose run crawler crawl --url https://bitarchivist.net --scopeType page --collection ua-suffix --generateWACZ --userAgentSuffix "+MyCrawler, info@example.com"
```

I see the user agent is logged as:

```
{"logLevel":"info","timestamp":"2023-04-20T19:05:31.097Z","context":"general","message":"User agent: \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.119 Safari/537.36 +MyCrawler, info@example.com\"","details":{}}
```

**Comment by anjackson** [comment]
Ah, thanks @tw4l. I think perhaps the issue is that I'm trying to pass it in from the [`values.yaml` in Browsertrix Cloud](https://github.com/webrecorder/browsertrix-cloud/blob/a2435a013b5d70ea561d1069969eaabc4b11a8d6/chart/values.yaml#L154), and I'm not getting the escaping right.

...Yes, looks like I'm hitting this:  https://github.com/helm/helm/issues/1994 which apparently can be fixed but I can't quite work out how to get the right quoting through the various layers of values/configmap/template/result.

**Comment by tw4l** [comment]
Ah okay! Thanks for opening the other issue!
