### ISSUE TITLE
Browsertrix can't fetch articles to crawl list (only menu items)

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#295]
Main Seed: http://diepresse.com

**Command Start:**

docker run -d -p 9709:9709 -v  $PWD/crawls/:/crawls/ webrecorder/browsertrix-crawler crawl --screencastPort 9709 --url http://diepresse.com --scopeType prefix --depth 3 --workers 2  --limit 99 --timeLimit 3600 --logging stats,pywb,debug  

**Description:**

No difference if Browsertrix was started with seedList or yaml config or --url Parameter.
Btrix Crawl is in no case able to generate the seeds for the articles out of the main page!

The site diepresse.com I was crawling already some times with preverious versions of Btrix and it was generating the follow up seeds to get into the articles correctly!
I can not tell excactly in which version the error firstly occured, but I guess it is related to the change of the puppeteer class before 0.9
(I have only some WARC Files from March where the articles are inside, but the rest like log files is gone)

**Other Tries:**

I really tried a lot of things, for example in the browsertrix-cloud the site was crawled without articles as well, but with the menu structure. If i start the same crawl like in the start line with the seed: http://www.diepresse.com and scopeType domain I get excactly the same result like in the Btrix-Cloud.

As the medias on this site are in a subdomain I even tried the scope any, but in pages.json there was still no single article but like in the Btrix-Cloud all sub-pages (Categories)

Last thing I tried was to use an article - URL as Main Seed and see if Btrix is able to open the site, which was working, but generating seeds for other articles fails as well, with the same result, I got only 1 Article, this was the main seed, and the rest of the crawl was only the category pages from the menu

cat pages.json 
{"format":"json-pages-1.0","id":"pages","title":"All Pages","hasText":false}
{"id":"6e1eed48-6bac-4314-822f-dfc61eca03d3","url":"https://diepresse.com/club/","title":"Club | DiePresse.com","loadState":4}
{"id":"f715b54d-83c6-41df-aeb3-1669fc14ba4c","url":"http://diepresse.com/","title":"Nachrichten | DiePresse.com","loadState":4,"seed":true}

Log File:

{"logLevel":"info","timestamp":"2023-04-24T09:38:17.533Z","context":"general","message":"Browsertrix-Crawler 0.9.0 (with warcio.js 1.6.2 pywb 2.7.3)","details":{}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:17.535Z","context":"general","message":"Seeds","details":[{"url":"http://diepresse.com/","include":["/^https?:\\/\\/diepresse\\.com\\//"],"exclude":[],"scopeType":"prefix","sitemap":false,"allowHash":false,"maxExtraHops":0,"maxDepth":3}]}
{"logLevel":"info","timestamp":"2023-04-24T09:38:17.657Z","context":"healthcheck","message":"Healthcheck server started on 9377","details":{}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:19.715Z","context":"worker","message":"Creating 1 workers","details":{}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:19.716Z","context":"worker","message":"Worker starting","details":{"workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:19.992Z","context":"worker","message":"Starting page","details":{"workerid":0,"page":"http://diepresse.com/"}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:19.999Z","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":0,"total":1,"pending":1,"limit":{"max":99,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2023-04-24T09:38:19.720Z\",\"url\":\"http://diepresse.com/\",\"added\":\"2023-04-24T09:38:17.835Z\",\"depth\":0}"]}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:20.187Z","context":"general","message":"Awaiting page load","details":{"page":"http://diepresse.com/","workerid":0}}
{"logLevel":"warn","timestamp":"2023-04-24T09:38:32.942Z","context":"general","message":"Invalid Seed - URL must start with http:// or https://","details":{"url":"javascript:window.__tcfapi('showConsentManager')","page":"http://diepresse.com/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:32.967Z","context":"behavior","message":"Running behaviors","details":{"frames":1,"frameUrls":["https://www.diepresse.com/"],"page":"http://diepresse.com/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:32.968Z","context":"behavior","message":"Run Script Started","details":{"frameUrl":"https://www.diepresse.com/","page":"http://diepresse.com/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:33.498Z","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.diepresse.com/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:38:33.500Z","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.diepresse.com/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:06.225Z","context":"behavior","message":"Run Script Finished","details":{"frameUrl":"https://www.diepresse.com/","page":"http://diepresse.com/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:06.230Z","context":"behavior","message":"Behaviors finished","details":{"finished":1,"page":"http://diepresse.com/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:06.233Z","context":"pageStatus","message":"Page Finished","details":{"loadState":4,"page":"http://diepresse.com/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:06.298Z","context":"worker","message":"Starting page","details":{"workerid":0,"page":"https://diepresse.com/club/"}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:06.300Z","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":1,"total":2,"pending":1,"limit":{"max":99,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2023-04-24T09:39:06.297Z\",\"url\":\"https://diepresse.com/club/\",\"added\":\"2023-04-24T09:38:32.866Z\",\"depth\":1}"]}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:06.989Z","context":"general","message":"Awaiting page load","details":{"page":"https://diepresse.com/club/","workerid":0}}
{"logLevel":"warn","timestamp":"2023-04-24T09:39:12.891Z","context":"general","message":"Invalid Seed - URL must start with http:// or https://","details":{"url":"javascript:window.__tcfapi('showConsentManager')","page":"https://diepresse.com/club/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:12.905Z","context":"behavior","message":"Running behaviors","details":{"frames":1,"frameUrls":["https://www.diepresse.com/club"],"page":"https://diepresse.com/club/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:12.906Z","context":"behavior","message":"Run Script Started","details":{"frameUrl":"https://www.diepresse.com/club","page":"https://diepresse.com/club/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:13.460Z","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.diepresse.com/club","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:13.461Z","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.diepresse.com/club","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:29.824Z","context":"behavior","message":"Run Script Finished","details":{"frameUrl":"https://www.diepresse.com/club","page":"https://diepresse.com/club/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:29.826Z","context":"behavior","message":"Behaviors finished","details":{"finished":1,"page":"https://diepresse.com/club/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:29.827Z","context":"pageStatus","message":"Page Finished","details":{"loadState":4,"page":"https://diepresse.com/club/","workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:29.861Z","context":"worker","message":"Worker exiting, all tasks complete","details":{"workerid":0}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:30.028Z","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":2,"total":2,"pending":0,"limit":{"max":99,"hit":false},"pendingPages":[]}}
{"logLevel":"info","timestamp":"2023-04-24T09:39:30.028Z","context":"general","message":"Waiting to ensure pending data is written to WARCs...","details":{}}

Find also attached the log file with debug flag  pywb.log and pages.json
[pywb.log](https://github.com/webrecorder/browsertrix-crawler/files/11310404/pywb.log)
[crawl-20230424104914259.log](https://github.com/webrecorder/browsertrix-crawler/files/11310405/crawl-20230424104914259.log)

**Comment by gitreich** [comment]
sorry for that one, if the url is http://www.diepresse.com it works correctly

docker run -d -p 9709:9709 -v $PWD/crawls/:/crawls/ webrecorder/browsertrix-crawler crawl --screencastPort 9709 --url http://www.diepresse.com --scopeType prefix --depth 3 --workers 2 --limit 99 --timeLimit 3600 --logging stats,pywb,debug

**Comment by tw4l** [comment]
@gitreich no worries! sounds like this was a configuration issue so I'm closing the issue, but feel free to comment if that's not the case :)
