### ISSUE TITLE
Not all images in srcset are scraped

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/browsertrix-crawler#3]
Working on https://github.com/openzim/zimit/issues/70 I ended up finding that I get different results for different runs of the same query.

Using `--url "https://mesquartierschinois.wordpress.com/2014/07/18/que-faire/"` on three consecutive runs, I got the following A articles for the first image on that page (`img_9104.jpg`)

**run1**

- `A/mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=1024&h=765`
- `A/mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=300&h=224`
- `A/mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=640&h=478'`

**run2**

- `A/mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=1280&h=956`
- `A/mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=640&h=478`

**run3**

- `A/mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=1024&h=765`
- `A/mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=640&h=478`

**run4**
- `A/mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=640&h=478`

The full list from srcset is:

```
https://mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=640&amp;h=478 640w,
https://mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=1280&amp;h=956 1280w,
https://mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=150&amp;h=112 150w,
https://mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=300&amp;h=224 300w,
https://mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=768&amp;h=574 768w,
https://mesquartierschinois.files.wordpress.com/2014/07/img_9104.jpg?w=1024&amp;h=765 1024w
```

The *fallback* on `src` is the `640w` one which got included in all 3 runs.

Given the very same args (only url and name) were specified, I'm confident this is unrelated to image selection by the browser (it's always using the *default* mobile device) and the replayer works fine is the (dynamic) requested image is in the ZIM.

I've looked into `autofetcher.js` but couldn't find a problem. When injected in a running browser, it attempts to `fetch` all the links. I couldn't get it to output to the crawler process as this is running inside the launched browser so I'm not sure what is exactly happening. When testing manually, I had to disable CORS in chrome but that shouldn't apply here.

Note: I am mentioning ZIM articles here as this is easier to manipulate but checked the WARC files and it matches the content of the ZIM.

**Comment by ikreymer** [comment]
Thanks for testing this in the browser! That does seem very strange, perhaps there is a timing issue and it moves to next page too quickly before they can be fetched.. There is not anything waiting to ensure the autofetcher is fully finished..

Could you try running with `--waitUntil networkidle0` to see if that makes a difference? If not, maybe need to have additional waiting options.

**Comment by rgaudin** [comment]
Ah, that's it! Worked with `networkidle0`.

**Comment by kelson42** [comment]
What should be done here? Should this working configuration the default one?

**Comment by ikreymer** [comment]
One thing to try is to update the autofetch script to cause an additional wait as soon as any autofetching is started, similar to videos.. Need to test if that would be sufficient..
I dont know if networkidle0 is always the best option, I think I've seen some pages work better with waiting for load event..

**Comment by ikreymer** [comment]
It turns out its possible to wait for both networkidle0 and load events simply by passing an array to `waitUntil`.
The command-line option defaults to `load,networkidle0` and I think that should do it for this use case.
Tested with the example linked and the srcsets seem to be getting captured.

**Comment by kelson42** [comment]
@ikreymer Thank you. Would that be possible to make it available soon in a release?
