### ISSUE TITLE
Entire site is crawled, but no output warcs are generated.

### ISSUE THREAD

**Issue by ArtHoff** [webrecorder/browsertrix-crawler#315]
Hi, I'm crawling a SharePoint intranet site (using the cntlm proxy) and browsertrix completes the crawl.

Via the screencast port I can see the pages it accesses during the crawl.
Unfortunately the pages are not scrolled and browsertrix does not create any warc files.

I've attached a text file with the crawler's output, in the hope that someone may be able to point me in the right direction.
Thank you so much for any help you can offer.

[no-WARC-truncated.txt](https://github.com/webrecorder/browsertrix-crawler/files/11515032/no-WARC-truncated.txt)

**Comment by tw4l** [comment]
There's a WIP branch you could try that records the network traffic via the browser rather than via the pywb proxy, but it's still in development so YMMV: https://github.com/webrecorder/browsertrix-crawler/tree/recorder-work

**Comment by ArtHoff** [comment]
Hi @tw4l - Thank you so much for this information.
I am currently trying the recorder-work branch. So far with the limited testing I've been able to do, it appears to be working.
I'm looking forward to a future stable release of the crawler that won't need proxy support for writing WARCS.
