### ISSUE TITLE
Bug in the page.json, missing comma between json blocks },{

### ISSUE THREAD

**Issue by philippeantonietti** [webrecorder/browsertrix-crawler#327]
content from a pages.jsonl :

`{"format":"json-pages-1.0","id":"pages","title":"All Pages","hasText":true}
{"id":"e5e60e60-9a02-4a18-9bb4-bb89414f71aa","url":"https://example.com/","title":null,"loadState":1,"seed":true}
`

above is not a valid json, this cause all sort of problems when trying to read, the correct must have a comma like :

`{"format":"json-pages-1.0","id":"pages","title":"All Pages","hasText":true},
{"id":"e5e60e60-9a02-4a18-9bb4-bb89414f71aa","url":"https://example.com/","title":null,"loadState":1,"seed":true}
`

**Comment by rgaudin** [comment]
No, adding that comma would not make it valid JSON.
Those are two separate JSON documents. JSON Lines as it name suggests is for individual JSON documents on each line. It's not a big document, it's one per line.

Your example shows them on the same line, that might be a line ending issue on your end.

**Comment by ikreymer** [comment]
Again, format here is JSONL, not JSON

**Comment by philippeantonietti** [comment]
Well, I don't know, fells like is not a very standard unless if I am missing a point...

Please don't take me wrong what the project achieved is remarkable ! but I never heard of JSONL however I am sure every developer heard of JSON, (specially web devs) 

I don't understand why not use JSON as you can create as many child elements needed, so rather than having one line per JSON than you would have nodes 

Also sounds very bad idea having to relay in /n /r new line as it can vary between OS so can easily break, is this register as file in the file extension database repository PRONOM ?

The implication is that I cannot unmarshall / deserialized with standard libraries nor able to validate output easily

**Comment by rgaudin** [comment]
@philippeantonietti, you were provided the link to jsonlines.org ; I think it would have answered most of your question.

The reason for using JSONLines here is to be able to scale. No matter how many millions of entries you have, you just need to have 1 single JSON document in memory to write it or to parse it.

It's still valid JSON, but one document per line. If you want to validate the whole file, just iterate over lines and validate JSON documents one by one.
