### ISSUE TITLE
Twitter post and timeline captures not working

### ISSUE THREAD

**Issue by tw4l** [webrecorder/browsertrix-crawler#339]
Twitter captures are not working as expected, even with a logged-in profile, which is now necessary due to Twitter [ending public unauthenticated access to Tweets](https://techcrunch.com/2023/06/30/twitter-now-requires-an-account-to-view-tweets/).

The page loads and Twitter behavior runs, but:

- There is no pages directory/pages.jsonl in the resulting WACZ
- Consequently, no pages are listed in replayweb.page
- If entering the captured tweet URL directly in replayweb.page, what's displayed is a "Something went wrong" message from Twitter:

![Image](https://github.com/webrecorder/browsertrix-crawler/assets/6758804/1773d006-2f5a-4ba6-a673-48afb47178b1)

- Digging into the devtools network tab in replayweb.page, the GET request for the tweet seems to return a "Javascript is not available" HTML page - not sure if this is the cause or a red herring:

![Image](https://github.com/webrecorder/browsertrix-crawler/assets/6758804/d9c3c69d-c7cf-45fc-8822-cb89b2ed36a6)

- Digging into the WACZ logs, it appears that the logs complete before logging successful WACZ creation, and the HEAD request to Twitter returns 403. Everything else seems okay from my initial look.

This has been reproed several times on different machines and from different IP addresses.

**Comment by tw4l** [comment]
Partially fixed by https://github.com/webrecorder/browsertrix-crawler/pull/340, which disables service workers using the new puppeteer method.

**Comment by tw4l** [comment]
Latest crawler tested on individual tweets and working well!

**Comment by tw4l** [comment]
Latest crawler main with browsertrix-behaviors 0.5.1 has account timelines working again as expected as well.

Testing with the home timeline only the first four tweets seem to be captured - we may need to tweak the behaviors a bit further there.

**Comment by ikreymer** [comment]
> Testing with the home timeline only the first four tweets seem to be captured - we may need to tweak the behaviors a bit further there.

FWIW, was able to get the behavior to go through home on my own account in ArchiveWeb.page, so may vary depending on account and location.. Profiles and threads are generally more important, but can take a look at that as well later.

**Comment by tw4l** [comment]
Fixed in latest main. New behaviors work as expected in twitter home timeline in archiveweb.page, can investigate further with browsertrix-crawler but since that's a much less common crawler target than accounts or individual posts, closing for now and we can open a new issue for it as needed.
