### ISSUE TITLE
Reaching sizeLimit value deletes all crawl data

### ISSUE THREAD

**Issue by ldko** [webrecorder/browsertrix-crawler#344]
I was running a crawl with `--sizeLimit 100000000000`, and looking at the log on my screen, the size limit was reached and the crawl was stopped as I would expect, but then it seems that all of the data for the crawl was deleted. I still have a crawls/collections/ directory that was created on disk, but it is empty. I had verified there was a collection directory for my crawl and that WARCs were written there while the crawl was going on. Is that the expected behavior? I see in crawler.js where if [sizeLimit is reached](https://github.com/webrecorder/browsertrix-crawler/blob/442f4486d3f684954ddef13fe5feee29f9f2344e/crawler.js#L629):

```
    if (this.params.sizeLimit) {
      if (size >= this.params.sizeLimit) {
        logger.info(`Size threshold reached ${size} >= ${this.params.sizeLimit}, stopping`);
        interrupt = true;
        this.clearOnExit = true;
```

it looks like it [deletes the data](https://github.com/webrecorder/browsertrix-crawler/blob/442f4486d3f684954ddef13fe5feee29f9f2344e/crawler.js#L822):
```
      if (this.clearOnExit) {
        logger.info(`Clearing ${this.collDir} before exit`);
        try {
          fs.rmSync(this.collDir, { recursive: true, force: true });
```

This is how I ran the crawl:

docker run -v $PWD/untspr2023_browsertrix.urls:/app/seedFile.txt -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl --seedFile /app/seedFile.txt --generateWACZ --scopeType  page --generateCDX --diskUtilization 95 --description "Video embeds from untspr2023 crawl" --warcinfo.operator "University of North Texas Libraries" --collection untspr2023_yt_embeds  --delay 5 --timeout 1000 --logging stats,behaviors,debug --sizeLimit 100000000000 --timeLimit 54000 --healthCheckPort 6065 --waitOnDone --behaviorTimeout 3000

I am attaching part of the log I was able to copy from my screen's stdout, [browsertrix-crawler_end.log](https://github.com/webrecorder/browsertrix-crawler/files/12054049/browsertrix-crawler_end.log), since the log on disk was deleted :) . I assume this isn't the intended behavior if for no other reason than the log shows that it created the WACZ just before deleting it. Anyway, I can crawl without `sizeLimit`, but this seems like it could be a bug.

**Comment by ikreymer** [comment]
Yes, this is definitely a bug! The idea for this was that it was intended for Browsertrix Cloud usage, where the current data would be packaged into WACZ, uploaded and previous data would be deleted to free up space for further crawling.
However, as is, it deletes after every time the size limit is reached!

Adding a fix that will only delete data if it has been uploaded.

Could also add an extra flag, --deleteAfterUpload that will further restrict this behavior to when the flag is provided.
I suppose you'd generally want this when uploading WACZ files, but could also keep data for whatever reason, eg. to recreate a larger WACZ, etc.. Maybe that's the safest option?
