### ISSUE TITLE
New release numbering?

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/browsertrix-crawler#350]
Release number (including tag and docker tag) switched from `0.10.2` to `v0.10.3`. Is this on purpose (and thus the new normal) or is it an accident?

**Comment by ikreymer** [comment]
Yes, this was intentional, trying to standardize our versioning. Most of our other tags starting with `v` as recommended and this was an oversight here. Is it causing problems for you, or just need to make an update?

**Comment by rgaudin** [comment]
Nope, just wanted to know if it was to stay

**Comment by ikreymer** [comment]
Question answered!

**Comment by ikreymer** [comment]
Er, revisiting this again, the docker tags will start with `v` but the docker images should continue to just be eg: `webrecorder/browsertrix-crawler:0.11.1`. The github tag release was intentional, docker tag was accidental!
Fixed with 0.11.1 and GH action update #386
