### ISSUE TITLE
Last Line of Logs - Docker Logs versus written Crawl Log

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#365]
Using v0.10.4
The las line:
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.506Z","context":"general","message":"Crawl status: done","details":{}}
seems not to be written in the LogFile in the collection Folder; 
The crawl is the most easiest crawl possible: A page with one image and one text; no links and nothing!

But it can be found in the logs of the docker container with the command:
docker logs image_id

here are 2 simple examples:
A from the crawl/collection/folder:
{"logLevel":"info","timestamp":"2023-09-05T09:07:12.168Z","context":"general","message":"Browsertrix-Crawler 0.10.4 (with warcio.js 1.6.2 pywb 2.7.4)","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:12.169Z","context":"general","message":"Seeds","details":[{"url":"https://www.vollmilch.at/","include":["/^https?:\\/\\/www\\.vollmilch\\.at\\//"],"exclude":[],"scopeType":"prefix","sitemap":false,"allowHash":false,"maxExtraHops":0,"maxDepth":3}]}
{"logLevel":"info","timestamp":"2023-09-05T09:07:12.249Z","context":"healthcheck","message":"Healthcheck server started on 16320","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.272Z","context":"state","message":"Storing state via Redis redis://localhost:6379/0 @ key prefix \"be66b52e0ebc\"","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.272Z","context":"state","message":"Max Page Time: 251 seconds","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.276Z","context":"general","message":"Text Extraction: Disabled","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.339Z","context":"screencast","message":"Screencast server started on: 9921","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.340Z","context":"general","message":"Queuing url https://www.vollmilch.at/","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.391Z","context":"healthcheck","message":"health check ok, num errors 0 < 1","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.409Z","context":"healthcheck","message":"health check ok, num errors 0 < 1","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.089Z","context":"worker","message":"Creating 1 workers","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.090Z","context":"worker","message":"Worker starting","details":{"workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:13.098Z","context":"worker","message":"Getting page in new window","details":{"workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:13.272Z","context":"screencast","message":"Start Screencast","details":{"workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.319Z","context":"worker","message":"Starting page","details":{"workerid":0,"page":"https://www.vollmilch.at/"}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.323Z","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":null,"total":null,"pending":1,"failed":0,"limit":{"max":500,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2023-09-05T09:07:13.096Z\",\"url\":\"https://www.vollmilch.at/\",\"added\":\"2023-09-05T09:07:12.343Z\",\"depth\":0}"]}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:13.325Z","context":"memory","message":"Memory","details":{"maxHeapUsed":34908560,"maxHeapTotal":75894784,"rss":121573376,"heapTotal":75894784,"heapUsed":34908560,"external":1976567,"arrayBuffers":143861}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.606Z","context":"general","message":"Awaiting page load","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:15.384Z","context":"behaviorScript","message":"Enable AutoFetcher","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:15.384Z","context":"behaviorScript","message":"Enable Autoplay","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:15.386Z","context":"behaviorScript","message":"Starting Autoscroll","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:16.338Z","context":"general","message":"Check CF Blocking","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:17.358Z","context":"general","message":"Extracting links","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.364Z","context":"behavior","message":"Running behaviors","details":{"frames":1,"frameUrls":["https://www.vollmilch.at/"],"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.365Z","context":"behavior","message":"Run Script Started","details":{"frameUrl":"https://www.vollmilch.at/","page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:17.367Z","context":"behaviorScript","message":"Starting Autoscroll","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:17.368Z","context":"behaviorScript","message":"Waiting for behaviors to finish","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.369Z","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.369Z","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:17.369Z","context":"behaviorScript","message":"All Behaviors Done for https://www.vollmilch.at/","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.370Z","context":"behavior","message":"Run Script Finished","details":{"frameUrl":"https://www.vollmilch.at/","page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.371Z","context":"behavior","message":"Behaviors finished","details":{"finished":1,"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.371Z","context":"general","message":"Waiting 1 seconds before moving on to next page","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.372Z","context":"pageStatus","message":"Page Finished","details":{"loadState":4,"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.397Z","context":"worker","message":"Worker exiting, all tasks complete","details":{"workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.495Z","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":1,"total":1,"pending":0,"failed":0,"limit":{"max":500,"hit":false},"pendingPages":[]}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:18.496Z","context":"memory","message":"Memory","details":{"maxHeapUsed":38046104,"maxHeapTotal":75894784,"rss":124469248,"heapTotal":75894784,"heapUsed":38046104,"external":3255506,"arrayBuffers":283391}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.497Z","context":"general","message":"Waiting to ensure pending data is written to WARCs...","details":{}}

B from the Docker Logs

{"logLevel":"debug","timestamp":"2023-09-05T09:07:11.199Z","context":"init","message":"Writing log to: /crawls/collections/vollmilch_20230905110709/logs/crawl-20230905090711198.log","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:12.168Z","context":"general","message":"Browsertrix-Crawler 0.10.4 (with warcio.js 1.6.2 pywb 2.7.4)","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:12.169Z","context":"general","message":"Seeds","details":[{"url":"https://www.vollmilch.at/","include":["/^https?:\\/\\/www\\.vollmilch\\.at\\//"],"exclude":[],"scopeType":"prefix","sitemap":false,"allowHash":false,"maxExtraHops":0,"maxDepth":3}]}
{"logLevel":"info","timestamp":"2023-09-05T09:07:12.249Z","context":"healthcheck","message":"Healthcheck server started on 16320","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.272Z","context":"state","message":"Storing state via Redis redis://localhost:6379/0 @ key prefix \"be66b52e0ebc\"","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.272Z","context":"state","message":"Max Page Time: 251 seconds","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.276Z","context":"general","message":"Text Extraction: Disabled","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.339Z","context":"screencast","message":"Screencast server started on: 9921","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.340Z","context":"general","message":"Queuing url https://www.vollmilch.at/","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.391Z","context":"healthcheck","message":"health check ok, num errors 0 < 1","details":{}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:12.409Z","context":"healthcheck","message":"health check ok, num errors 0 < 1","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.089Z","context":"worker","message":"Creating 1 workers","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.090Z","context":"worker","message":"Worker starting","details":{"workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:13.098Z","context":"worker","message":"Getting page in new window","details":{"workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:13.272Z","context":"screencast","message":"Start Screencast","details":{"workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.319Z","context":"worker","message":"Starting page","details":{"workerid":0,"page":"https://www.vollmilch.at/"}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.323Z","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":null,"total":null,"pending":1,"failed":0,"limit":{"max":500,"hit":false},"pendingPages":["{\"seedId\":0,\"started\":\"2023-09-05T09:07:13.096Z\",\"url\":\"https://www.vollmilch.at/\",\"added\":\"2023-09-05T09:07:12.343Z\",\"depth\":0}"]}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:13.325Z","context":"memory","message":"Memory","details":{"maxHeapUsed":34908560,"maxHeapTotal":75894784,"rss":121573376,"heapTotal":75894784,"heapUsed":34908560,"external":1976567,"arrayBuffers":143861}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:13.606Z","context":"general","message":"Awaiting page load","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:15.384Z","context":"behaviorScript","message":"Enable AutoFetcher","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:15.384Z","context":"behaviorScript","message":"Enable Autoplay","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:15.386Z","context":"behaviorScript","message":"Starting Autoscroll","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:16.338Z","context":"general","message":"Check CF Blocking","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:17.358Z","context":"general","message":"Extracting links","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.364Z","context":"behavior","message":"Running behaviors","details":{"frames":1,"frameUrls":["https://www.vollmilch.at/"],"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.365Z","context":"behavior","message":"Run Script Started","details":{"frameUrl":"https://www.vollmilch.at/","page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:17.367Z","context":"behaviorScript","message":"Starting Autoscroll","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:17.368Z","context":"behaviorScript","message":"Waiting for behaviors to finish","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.369Z","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.369Z","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:17.369Z","context":"behaviorScript","message":"All Behaviors Done for https://www.vollmilch.at/","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.370Z","context":"behavior","message":"Run Script Finished","details":{"frameUrl":"https://www.vollmilch.at/","page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.371Z","context":"behavior","message":"Behaviors finished","details":{"finished":1,"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:17.371Z","context":"general","message":"Waiting 1 seconds before moving on to next page","details":{"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.372Z","context":"pageStatus","message":"Page Finished","details":{"loadState":4,"page":"https://www.vollmilch.at/","workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.397Z","context":"worker","message":"Worker exiting, all tasks complete","details":{"workerid":0}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.495Z","context":"crawlStatus","message":"Crawl statistics","details":{"crawled":1,"total":1,"pending":0,"failed":0,"limit":{"max":500,"hit":false},"pendingPages":[]}}
{"logLevel":"debug","timestamp":"2023-09-05T09:07:18.496Z","context":"memory","message":"Memory","details":{"maxHeapUsed":38046104,"maxHeapTotal":75894784,"rss":124469248,"heapTotal":75894784,"heapUsed":38046104,"external":3255506,"arrayBuffers":283391}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.497Z","context":"general","message":"Waiting to ensure pending data is written to WARCs...","details":{}}
{"logLevel":"info","timestamp":"2023-09-05T09:07:18.506Z","context":"general","message":"Crawl status: done","details":{}}

**Comment by ikreymer** [comment]
Thanks for pointing this out, was initially confused by this myself.
We were actually closing the file log on purpose, because it was being written to the WACZ files. However, this was confusing because it was happening even if a WACZ was not being generated, and no additional message was logged.
To address this, the PR adds the following:
- Prints a message that 'crawling is done' before any post-crawl operations start, so there is another entry after 'waiting for pending data'
- When WACZ generation is enabled also prints a final message that this is the last line of the log file, after which the file will be added to the WACZ.
It seems that closing the log file is not specifically necessary, so the log file outside of WACZ may have the final crawl done line as well.
Hope this clears things up and should be a bit more clear after the fix is added.
