### ISSUE TITLE
Cloudflare security page is saved instead of real content

### ISSUE THREAD

**Issue by benoit74** [webrecorder/browsertrix-crawler#387]
On some sites (we encountered it on [radiopaedia.org](https://radiopaedia.org/), see https://github.com/openzim/zimit/issues/217), the crawler is saving Cloudflare security page instead of the real content.

We have tons of pages like this one which are recorded:
![image](https://github.com/webrecorder/browsertrix-crawler/assets/7102089/4bad4f82-df3e-4ee7-b73c-a6059092a6ef)

This is close to #372 but not identical (there is no error and the crawler considers that job is done).

We don't think there's much that can be done technically but at least we prefer to ask and probably this should be documented somewhere as a known limitation.

**Comment by wsdookadr** [comment]
Cloudflare's new captcha [requires Chrome >= 115](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1404#issue-1814143857).
At the present time, Browsertrix [offers Chrome 112](https://github.com/webrecorder/browsertrix-browser-base/releases/tag/chrome-112).

**Comment by benoit74** [comment]
Thank you a lot for finding this upstream issue.
FYI, I'm right now doing a local test with Chrome 117

**Comment by benoit74** [comment]
I'm struggling to reproduce this issue on my dev machine, so I cannot really test the update to Chrome 117.

I've built a Docker image based on "google-chrome-stable 117.0.5938.88-1 amd64" and it is currently running on the machine which encountered this issue, I will update you once I have feedback.

**Comment by wsdookadr** [comment]
Apparently you also need to [create a profile](https://github.com/webrecorder/browsertrix-crawler#creating-and-using-browser-profiles) and the environment inside the container [needs to have proper locale and timezone](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1404#issuecomment-1655861149).

**Comment by ikreymer** [comment]
@wsdookadr @benoit74 We've been held up by the lack of Linux Chromium updates ARM64. We will probably switch to Brave for this reason: https://github.com/webrecorder/browsertrix-crawler/issues/189#issuecomment-1731554979
which is up-to-date with latest Chromium.

For locale, we already have the --lang setting, can consider adding other settings (within reason) if it will help avoid Cloudflare blocking. My impression is that it may be another cat-and-mouse kind of situation to avoid this block, so haven't spent time on it yet. If you have suggestions that we can implement, let us know, and PRs welcome also!

**Comment by benoit74** [comment]
I don't achieve to get a repro, not with Chrome 117, not with Chrome 112. 
I don't know exactly what led to this situation.
I will close this issue and re-open if I achieve to get a repro, it's impossible to make any progress otherwise. Do not hesitate to reopen it if you have a repro on your side.
Thank you all for the good pointers in any case.

**Comment by rgaudin** [comment]
@benoit74 can you open one requesting browsertrix to handle [429](https://www.rfc-editor.org/rfc/rfc6585#section-4) responses? In this case, Cloudflare was sending proper 429 responses and it's insensible of the crawler to ignore them

**Comment by benoit74** [comment]
@rgaudin done: https://github.com/webrecorder/browsertrix-crawler/issues/392
