### ISSUE TITLE
alternative ways of implementing browser behaviors

### ISSUE THREAD

**Issue by wsdookadr** [webrecorder/browsertrix-crawler#398]
I was looking at [browser-behaviors](https://github.com/webrecorder/browsertrix-behaviors/) but find it somewhat heavy to write a new behavior and then rebundle it somewhow with browsertrix to apply it to a situation.

Would it be viable to achieve the same by creating a browser profile with pre-bundled [violentmonkey](https://github.com/violentmonkey/violentmonkey) or [tampermonkey](https://github.com/Tampermonkey/tampermonkey) and then just mounting the site specific userscripts in the docker container to have them run on any page of some specific site? For my use-case I'd need to just have it click some buttons to unfold some threads in a web page. But overall I think there are [large](https://www.tampermonkey.net/scripts.php?locale=en) [repositories](https://greasyfork.org/en) of ready-made userscripts that can be leveraged in this way.

I was curious what you think of this.

If the answer is in the negative, I'd be interested what functionality is exclusively offered by [browser-behaviors](https://github.com/webrecorder/browsertrix-behaviors/).

**Comment by ikreymer** [comment]
You don't need to recompile browsertrix-behaviors, we are working on a system of extensible behaviors, already supported but not yet as well documented: https://github.com/webrecorder/browsertrix-crawler#additional-custom-behaviors

You can just mount behaviors into the crawler with `--customBehaviors`. There is a more in-depth tutorial here:
https://github.com/webrecorder/browsertrix-behaviors/blob/main/docs/TUTORIAL.md that covers the specific of creating behaviors, but basically it a class with a `run()` and `isMatch()` functions.

You can also look at the tests in: https://github.com/webrecorder/browsertrix-crawler/tree/main/tests/custom-behaviors

We are aware of tampermonkey/violentmonkey ecosystem, and it may make sense to try to support userscripts in the future, but for simplicity, wanted to just implement a pure JS solution without additional dependencies. We may add additional APIs specifically for crawling, such as a way to customize link extraction.

Will this work for your use case?

**Comment by wsdookadr** [comment]
> Will this work for your use case?

Yes, thank you! I will look into the resources you've shared :)
