### ISSUE TITLE
10GB wacz file - how to split?

### ISSUE THREAD

**Issue by eleaner** [webrecorder/browsertrix-crawler#401]
Hi,

I am new to this project and love it
it can crawl my squarespace held page - that's already  kudos
however the archive file has more than 10GB and does not open in https://replayweb.page

how should I manage it? 
I assume the same objects might be indexed a few times depending how are accessed

**Comment by ikreymer** [comment]
It's hard to say without looking at the file what the issue is. Do you need to split for size reasons, or are trying to figure out why it doesn't render in RWP? If you can share the file with us, we'll try to take a look, or share the url that doesn't replay.

**Comment by eleaner** [comment]
@ikreymer 
Thank you for your response.
I assumed that 10G single file might be too big - hence the idea of splitting it.
Maybe that's wrong assumption to start with. is 10G a normal size and should work?

I have the file locally
I can certainly make it available online and see if it renders from the url.
What would be the "best practice", archiving directly to the place that is available online?

**Comment by eleaner** [comment]
@ikreymer 
https://s3.kisiel.net.pl/qpixels.wacz/qpixels-20231001.wacz

this seems ti be working perfect - though I am still not sure why it is 10GB (I wasn't expecting it) and I am not sure which visible parts ara actually archived and which referenced to an online version

e.g.
https://replayweb.page/?source=https%3A%2F%2Fs3.kisiel.net.pl%2Fqpixels.wacz%2Fqpixels-20231001.wacz#view=pages&url=https%3A%2F%2Fwww.qpixels.com%2Ftravel-blog%2F2023%2F9%2Fni-tele-really-big-clock&ts=20231001102556

At the bottom there is youtube video. Is it actually archived?

Also, the same blog post can be accesses many different ways. Are the elements of this post multiplied in the wacz file?

**Comment by eleaner** [comment]
@ikreymer 
https://s3.kisiel.net.pl/qpixels.wacz/qpixels-20231001.wacz

this seems ti be working perfect - though I am still not sure why it is 10GB (I wasn't expecting it) and I am not sure which visible parts ara actually archived and which referenced to an online version

e.g.
https://replayweb.page/?source=https%3A%2F%2Fs3.kisiel.net.pl%2Fqpixels.wacz%2Fqpixels-20231001.wacz#view=pages&url=https%3A%2F%2Fwww.qpixels.com%2Ftravel-blog%2F2023%2F9%2Fni-tele-really-big-clock&ts=20231001102556

At the bottom there is youtube video. Is it actually archived?

Also, the same blog post can be accesses many different ways. Are the elements of this post multiplied in the wacz file?

**Comment by ikreymer** [comment]
> @ikreymer https://s3.kisiel.net.pl/qpixels.wacz/qpixels-20231001.wacz
> 
> this seems ti be working perfect - though I am still not sure why it is 10GB (I wasn't expecting it) and I am not sure which visible parts ara actually archived and which referenced to an online version
> 

That's great to hear! Yep, you can access it in replayweb.page while hosting the file on S3. You can also embed replayweb.page as per the [embedding guide](https://replayweb.page/docs/embedding) if you want to put the web archive into a different page.

If it loads on https://replayweb.page, it is 100% coming from the archive, as it can only load resources from the replayweb.page domain, which loads only from the WACZ file specified.

> e.g. https://replayweb.page/?source=https%3A%2F%2Fs3.kisiel.net.pl%2Fqpixels.wacz%2Fqpixels-20231001.wacz#view=pages&url=https%3A%2F%2Fwww.qpixels.com%2Ftravel-blog%2F2023%2F9%2Fni-tele-really-big-clock&ts=20231001102556
> 
> At the bottom there is youtube video. Is it actually archived?

Looks like the video plays, so it is in fact archived :)
We don't yet have a good way of browsing the contents, but you can use the URL tab to search by files, something we hope to improve in ReplayWeb.page 2.0

> 
> Also, the same blog post can be accesses many different ways. Are the elements of this post multiplied in the wacz file?

Possibly, you can do a URL search to see how many copies of a URL are archived, though crawler should be skipping exact duplicates.

Seems like the questions have been answered, and may be more appropriate for discussion on our [Forum](https://forum.webrecorder.net/) for further discussion.
