### ISSUE TITLE
Improved Text Extraction, stored to WARC

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/browsertrix-crawler#403]
Currently, we extract the initial text if the `--text` flag is set and add this to the pages.jsonl. However, this has proven not entirely scalable, especially if the text is very large. Instead, we should just extract the text and put it into WARCs as `resource` records, similar to screenshots, with type `text/plain`

Additionally, can extract text immediately after page load, as well as after behaviors run.

The resource records can be:
- `urn:text:<url>` for initial page load text
- `urn:textFinal:<url>` for text extracted after behaviors run.

Could further optimize and only store `textFinal` if it is different then initial text, allowing for better detection of when running behaviors causes the dynamic changes to the text of the page.

The idea would be that the CDXJ could then be searched for `urn:text:` or `urn:textFinal:` prefix to find all WARC records with extracted text, which could then be ingested directly into full-text search systems.

Some questions:
- Does `urn:text` and `urn:textFinal` make sense?
- Should there be a textFinal always, or only if different? Or should it be a `revisit` if unchanged from initial?
- Compared to screenshots, there is even more variability with how text is extracted. How should this metadata be reflected? There is the CDP function used (eg. DOMSnapshot.captureSnapshot) + extracting logic, which could change over time. For example, could put the extracting function as separate repo, and include its commit, something like:
`WARC-Json-Metadata: {"extractMethod": "DOMSnapshot.captureSnapshot", "extractParser": "https://github.com/webrecorder/extract-text-lib@abcdefg"}`
- Other ways to version text extraction for later comparison?

Feedback welcome!

**Comment by rgaudin** [comment]
Not using these texts yet but planning to, I'd actually prefer to have them in the WARC. Makes sense and WARC is flexible enough to filter them out easily.

I like the processing metadata.

Questions around text/textFinal could be resolved by requesting user to choose what he wants. A `--textInitial` and a `--textFinal` would settle this. I don't see how the initial text can be more useful than the final one… besides knowing if behavior changed anything but in that case it's a metadata or a debug info.

**Comment by edsu** [comment]
I like this proposal!

I wonder, would it be helpful to use the `conversion` record type instead of `resource` records, and then linking the record with `WARC-Refers-To`?

I'm a bit confused about what `urn:text:<url>` and `urn:textFinal:<url>` are here. Are they `WARC-Record-ID`s? I don't think those are valid [URN namespaces](https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml), which is a bit icky.

I'm interested to hear more about the use cases for initial and final text. I think a browsertrix behavior could potentially modify the page without modifying the text of the page?

**Comment by ikreymer** [comment]
> Questions around text/textFinal could be resolved by requesting user to choose what he wants. A `--textInitial` and a `--textFinal` would settle this. I don't see how the initial text can be more useful than the final one… besides knowing if behavior changed anything but in that case it's a metadata or a debug info.

Yes, that's something that can be customized via the cmdline option, but still thinking what is best default option. The 'initial text' is hopefully more consistent, captured as soon as window.onload event fires. The final text could be more varied, depending on how long behavior runs and what it does, so it could change.





> I wonder, would it be helpful to use the `conversion` record type instead of `resource` records, and then linking the record with `WARC-Refers-To`?

I'm not sure that it does, since its not a conversion of any single record, but rendering of the page, similar to screenshot.

> I'm a bit confused about what `urn:text:<url>` and `urn:textFinal:<url>` are here. Are they `WARC-Record-ID`s? I don't think those are valid [URN namespaces](https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml), which is a bit icky.

It would be `WARC-Target-URI: urn:text:https://example.com/` for text from `https://example.com/`.
We already do this for screenshots as, eg. `urn:screenshot:https://example.com/`. This makes it easier to search for all custom resources by searching for `urn:` - perhaps we should consider registering these?
Other tools just do `screenshot:https://example.com/` which is a bit less standard.
See: https://github.com/iipc/warc-specifications/issues/54#issuecomment-1544010328 for more examples of this
(and can continue standardization discussion in there)

> I'm interested to hear more about the use cases for initial and final text. I think a browsertrix behavior could potentially modify the page without modifying the text of the page?

Right, it definitely could, mostly for behaviors that involve scrolling and loading additional content on a page, it could be useful, and also detecting when behavior has definitely changed the page, though not guarantees other way around.
- Initial text is more consistent: the text on initial page load should be the same if page hasn't changed, and can be used to help detect changes.
- Final text is more complete: if text is used for full-text search, the final text should include everything after behavior has run, so all text that was loaded on that page, after scrolling. The amount of text loaded would still depend on how long behavior runs if there is infinite scroll. For something highly dynamic like Instagram, which dynamically shows/hides post, it still wouldn't get all the text, but could help for something like facebook, where comments are expanded in place / posts added at the bottom.
