### ISSUE TITLE
[Docs] More exclusion examples?

### ISSUE THREAD

**Issue by pato-pan** [webrecorder/browsertrix-crawler#416]
Perhaps a dedicated wikipage? I tried to use the exclusion rules ?updated-min=$ &updated-min=$ and it didn't work. But the exclusion rule /share-post.g$ works. I assume this is due to some incompatibility issue with the special characters. Since this is not documented, I'll have to find out on my own which one is causing this through testing (but it's probably =)

**Comment by pato-pan** [comment]
may be related to #394

**Comment by pato-pan** [comment]
I am lost on how exclusions on the yaml file work.... it doesn't seem to be doing anything, everything that should be excluded appears in replay.webpage. Here's my yaml file.

`seeds:
  - url: https://example.com/
    exclude:
      - updated-min=$
      - updated-max=$
      - ?updated-min=$
      - ?updated-max=$
      - &updated-min=$
      - &updated-max=$
      - /share-post.g$
      - /docs/securesc$
      - securesc$
      - doc-04-38-docs.googleusercontent.com/*
      - doc-04-38-docs.googleusercontent.com/docs/securesc*
      - doc-04-38-docs.googleusercontent.com
      - recaptcha$
      - youtubei$
      - example2.com/*
    blockRules:
      - inFrameURL: google.com/recaptcha
      - inFrameURL: youtube.com/youtubei
      - url: example2.com
      - url: doc-04-38-docs.googleusercontent.com
  - url: https://example2.com/
    exclude:
      - updated-min=$
      - updated-max=$
      - ?updated-min=$
      - ?updated-max=$
      - &updated-min=$
      - &updated-max=$
      - /share-post.g$
      - /docs/securesc$
      - securesc$
      - doc-04-38-docs.googleusercontent.com/*
      - doc-04-38-docs.googleusercontent.com
      - doc-04-38-docs.googleusercontent.com/docs/securesc*
      - recaptcha$
      - youtubei$
      - example.com/*
    blockRules:
      - inFrameURL: google.com/recaptcha
      - inFrameURL: youtube.com/youtubei
      - url: example.com
      - url: doc-04-38-docs.googleusercontent.com

# Note:       - &updated-min=$ works. & doesn't cause issues, I don't know about =
# Excluding this thing https://doc-04-38-docs.googleusercontent.com/docs/securesc/hgfsdgghngffdg is a pain in the head. The same audio gets downloaded 1k times because it's in every page. Is it always the same url at the start? I wonder. Update: It is, any other url that isn't doc-04-38 is a different file.
# why doesn't this /docs/securesc$ work!?!? by that logic /share-post.g$ also doesn't work!
# I am shocked doc-04-38-docs.googleusercontent.com/docs/securesc/* doesn't work.
# yeah, nothing here works.`

These exclusions are necessary for me because that audio file (doc-04-38) gets redownloaded so many times due to Google always providing a different url and the file appearing on every page. the "updated-" exclusions are necessary because that leads to the crawls to take forever, and these pages are not needed. Most users would not even be aware of them. An example of how it would be use is "example.com/search?updated-max=9 blah blah".

**Comment by pato-pan** [comment]
Nevermind? exclusions are made with regex, meaning recaptcha$ doesn't work because $ means "recaptcha" has to be at the end of the url and it isn't. The full url was something like "google.com/v2/recaptcha/hewjdbwieh?randomparametersstuffandmorestuff" $ points to the end of the string. I guess I should had known since the docs said it uses regex, but I am always stuff because some programs accept regex with some limitations or slight differences or misuse the word.

I still believe there should be more complex regex examples, I'll probably push a commit once I test some strings and make sure the examples I provide would work.

**Comment by ikreymer** [comment]
Thanks for the detailed feedback - yes, the exclusions use regexes, but you should be able to escape them with `\$`
We can include more complex examples. The exclusion rules also only apply to pages, the blockRules apply to any URL in the page.

Both methods built-in browser regular expressions. If you want a quick test to see if a regular expressions matches what you're looking for, you can try `new RegExp("updated-min=$").test("https://example.com/")` and see that it doesn't match, while `new RegExp("updated-min=\\$").test("https://example.com/?updated-min=$&a=b")` does match. Note that you'll need a double escape `\\$` for that.
We'll see if there's a way to make this simpler

**Comment by pato-pan** [comment]
Apologies on the late reply, I thought I had email notifications enabled on my email but they were on my other email.

When I created this issue I actually started writing my own update to the documentation to include more exclusions and fix some confusing wording (the word "skip" was used, but in that context it can be interpreted in two ways). I kind of got very busy trying to archive my website by turning it into documents instead of fixing my problems with regex and forgot to finish writing this new readme. Now that I am back, I had submitted a push request for this readme, please let me know if there are any issues or if I misunderstood something. I am not sure if every detail I included was necessary.

I should mention that I noticed that using brackets [] at the beggining of an url field will cause identation issues. I can't think of an use case for using those brackets at the beggining though (since you can use *. or just say google.com). Maybe that deserves it's own issue.

**Comment by tw4l** [comment]
Content from related PR has been added to new Browsertrix Crawler documentation site.
