### ISSUE TITLE
Update README.md to mention Brave instead of Chrome

### ISSUE THREAD

**Issue by benoit74** [webrecorder/browsertrix-crawler#441]
README.md still mention Chrome while since 0.12, crawler has switched to Brave. I think this should be fixed. Probably mention only mention Brave in first paragraph then add a detail somewhere later in the README about the fact that a transition from Chrome/Chromium to Brave happened at 0.12

**Comment by ikreymer** [comment]
This has been updated in the README (probably for the 1.x release).
