### ISSUE TITLE
Any way to save seed urls into separate collections?

### ISSUE THREAD

**Issue by halmos** [webrecorder/browsertrix-crawler#447]
Is there an existing config option that allows the yaml to specify multiple seed urls, and to archive them as separate collections? The default behavior seems to combine all seed urls as a single collection / wacz file.

**Comment by Shrinks99** [comment]
This behavior is generally availabe in [Browsertrix Cloud](https://browsertrix.com/), by creating multiple crawl workflows and adding the archived items they create to different collections (a specific feature of Browsertrix Cloud).  It is not something we plan to add directly to the crawler.

**Comment by ikreymer** [comment]
With the 1.x version, this is something that could in theory be in the future, but no plans for it at the moment. Would need to figure out how to handle crawl config/state saving, partial completion, as well as dedup, etc..

If you need to keep the crawl output completely separate, our recommendation is to start multiple crawl processes and manage them as needed.
