### ISSUE TITLE
[Bug]: no warc-info header in any warc file included in a wacz

### ISSUE THREAD

**Issue by tuehlarsen** [webrecorder/browsertrix-crawler#452]
### Browsertrix Cloud Version

v1.8.1-478b794

### What did you expect to happen? What happened instead?

Why do you not have a warc-info header in every produced warc file? Is it a bug?
e.g. rec-20231210070256037204-crawl-sched-03e01f26-37d-28369860-0.warc.gz
I have added the line numbers.

    1 WARC/1.0^M
    2 WARC-Type: response^M
    3 WARC-Record-ID: <urn:uuid:24fcf4ec-972a-11ee-970c-e61886277aa6>^M
    4 WARC-Target-URI: https://tv2.dk/^M
    5 WARC-Date: 2023-12-10T07:02:55Z^M
    6 WARC-IP-Address: 199.232.42.217^M
    7 Content-Type: application/http; msgtype=response^M
    8 Content-Length: 70397^M
    9 WARC-Payload-Digest: sha1:3I7AVM5N4NF2HJFQW263PCJVD4Z6TK6F^M
   10 WARC-Block-Digest: sha1:GZO7S6D4IKQXX2X5SXUATSDBXJ6HHL4A^M
   11 ^M
   12 HTTP/1.1 200 OK^M
   13 Connection: keep-alive^M

### Step-by-step reproduction instructions

see above

**Comment by tw4l** [comment]
Fixed in https://github.com/webrecorder/browsertrix-crawler/pull/556 :)
