### ISSUE TITLE
SOCKS proxy username and password parameters missing

### ISSUE THREAD

**Issue by vbanos** [webrecorder/browsertrix-crawler#453]
There are options to setup `SOCKS_HOST` and `SOCKS_PORT`
https://github.com/webrecorder/browsertrix-crawler?tab=readme-ov-file#configuring-chromium--puppeteer--pywb
but we also need to use a username and a password for some SOCKS proxies which require authentication.
These options would be very useful. Thank you.

**Comment by ikreymer** [comment]
This has been implemented via #589 (in 1.2.0-beta.0+), and you can set `PROXY_SERVER=socks://username:password@host` or pass the same via --proxyServer flag
