### ISSUE TITLE
URL cleaner: Where to contribute rules for browsertrix ?

### ISSUE THREAD

**Issue by Rexadev** [webrecorder/browsertrix-crawler#490]
browsertrix must use some kind URLCleaner(https://en.wikipedia.org/wiki/Clean_URL) something like https://github.com/ClearURLs/Addon.

**Comment by tw4l** [comment]
Hi @Rexadev, can you explain your use case and where you'd like the crawler to use a URL cleaner? Currently the crawler extracts links from within pages and uses those exact URLs for the pages, since that's the request that will be made on replay.

**Comment by Rexadev** [comment]
@tw4l If browsertrix  uses URLClearner I would like to contribute rules for it

**Comment by tw4l** [comment]
Hi @Rexadev, thanks for your interest but we do not use URLCleaner and unless there's a compelling use case likely won't, so I'm closing this for now. Feel free to comment/re-open if I'm missing something.
