### ISSUE TITLE
Brave Browser launch error

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#512]
Hi, I have a new error in Versiomn 1.0.2, here is the log File (I changed now on more detail lgging, maybe it's going to happen again):

`{"timestamp":"2024-03-25T13:15:10.194Z","logLevel":"error","context":"general","message":"Crawl failed","details":{"type":"exception","message":"Failed to launch the browser process!\n[41:41:0325/131510.161912:ERROR:brave_stats_updater.cc(104)] bad url given as stats updater url: url-source=http://invalid.dev/\n[41:41:0325/131510.163229:ERROR:ozone_platform_x11.cc(243)] Missing X server or $DISPLAY\n[41:41:0325/131510.163263:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n","stack":"Error: Failed to launch the browser process!\n[41:41:0325/131510.161912:ERROR:brave_stats_updater.cc(104)] bad url given as stats updater url: url-source=http://invalid.dev/\n[41:41:0325/131510.163229:ERROR:ozone_platform_x11.cc(243)] Missing X server or $DISPLAY\n[41:41:0325/131510.163263:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n\n    at ChildProcess.onClose (file:///app/node_modules/@puppeteer/browsers/lib/esm/launch.js:268:24)\n    at ChildProcess.emit (node:events:530:35)\n    at ChildProcess._handle.onexit (node:internal/child_process:294:12)"}}`

The command to start was:
`docker run -d --name ONB_Btrix_freizeit_medien_daily_20240325131501 -e NODE_OPTIONS="--max-old-space-size=32768" -p 9655:9655 -p 13819:13819  -v /home/netarchive/browsertrix/crawls/:/crawls/ webrecorder/browsertrix-crawler:1.0.2 crawl --screencastPort 9655 --seedFile /crawls/config/freizeit_medien_daily_seeds.txt   --scopeType prefix --depth 5 --extraHops 0 --workers 1 --healthCheckPort 13819  --delay 1 --waitUntil networkidle0  --saveState always   --timeLimit 10800  --sizeLimit 357286400  --logging stats,info --warcInfo ONB_CRAWL_freizeit_medien_daily_Depth_5_20240325131501 --userAgentSuffix +ONB_Bot_Btrix_1.0.2, webarchiv@onb.ac.at --crawlId id_ONB_CRAWL_freizeit_medien_daily_Depth_5_20240325131501 --collection freizeit_medien_daily_20240325131501
`
The SeedFile has been 2 seeds:
http://freizeit.at/
https://freizeit.at/info/impressum-freizeitat/401785646

No archive Folder was generated

On this Server browsertrix runs as root (because of the V1.0.0 bug)

The (virtual) Server got 15 GB RAM and no high loads
Ubuntu 22.04.4 LTS x86_64 up to date
Intel Xeon E5-2640 v4 (4) @ 2.399GHz 

First time I got a missing X Server error here
If it happens again i will post a more detail log here

**Comment by ikreymer** [comment]
Hm, it seems that the Xvfb server that the crawler starts failed to start for some reason. I assume this happened only once?
You could also try running with headless mode by adding the `--headless` flag, which should be fairly reliable at this point.

**Comment by gitreich** [comment]
correct it happened only once, no changes in config and it has not repeated since then

will comment here if i really went to --headless

**Comment by gitreich** [comment]
With --headless screencast is still possible
I moved with this server to use --headless flag for every crawl

**Comment by ikreymer** [comment]
Since this is not possible to repro, closing for now. I think the issue was with Xvfb launching for whatever reason, and there is a consistent workaround with headless mode.
