### ISSUE TITLE
--filename option in v 1.0.X removed or not?

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#513]
In the docs 
https://crawler.docs.browsertrix.com/user-guide/browser-profiles/#automated-profile-creation-for-user-login 
I can find the parameter --filename

But in the parameters:
https://crawler.docs.browsertrix.com/user-guide/cli-options/
--filename is removed

When I use it in Version 1.0.2 for creating profile it is not working!
Error from the Log File:
`{"timestamp":"2024-03-26T10:16:49.409Z","logLevel":"warn","context":"general","message":"HTTP Error","details":{"type":"exception","message":"Command failed: tar cvfz tiktok_new.tar.gz ./\ntar: .: file changed as we read it\n","stack":"Error: Command failed: tar cvfz tiktok_new.tar.gz ./\ntar: .: file changed as we read it\n\n    at checkExecSyncError (node:child_process:890:11)\n    at Module.execFileSync (node:child_process:926:15)\n    at Browser.saveProfile (file:///app/dist/util/browser.js:111:23)\n    at createProfile (file:///app/dist/create-login-profile.js:212:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InteractiveBrowser.handleRequest (file:///app/dist/create-login-profile.js:435:21)"}}`

Command I used:
docker run -p 6080:6080 -p 9223:9223 -v $PWD/crawls/profiles:/crawls/profiles/ -it webrecorder/browsertrix-crawler:1.0.2 create-login-profile  --filename "tiktok_new.tar.gz" --url "https://tiktok.com" --profile "/crawls/profiles/tiktok.tar.gz"

**Comment by tw4l** [comment]
Thanks @gitreich , and good catch on `--filename` being missing from the CLI options page - it looks like we only added the `help` text for the `crawl` entrypoint, and should add the options for the `create-login-profile` entrypoint as well.

The `--filename` option for `create-login-profile` should be working, so sounds like a bug. I will see if I can reproduce the issue.

**Comment by tw4l** [comment]
Interesting, I just got the same error locally with crawler 0.12.4.

**Comment by ikreymer** [comment]
The issue is the relative path is not a writable directory, maybe we should default it to `/crawls`. For now, you can use `--filename /crawls/profiles/tiktok_new.tar.gz` instead of `--filename tiktok_new.tar.gz`

**Comment by gitreich** [comment]
true with absolut path it is working as expected in V. 1.0.2
