### ISSUE TITLE
Content-Length: 0 in text.warc instead of text like in rec.warc

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#519]
in Btrix Version 1.0.2
In the regular warc File the content is their as expected;
But the generated text.warc contains no content only the message content-length 0
And: This problem occurs with Instagram, not with Facebook! With the same settings!
Addiditonal-hint: I also messed around with --text option and tried it several times, but none of the --text options was forcing a text.warc that had any content (should only --text work also? it's not generating text.warc and not adding text in the page.json)

This crawl i use to validate my browser profiles are still loged in, an it is very beneficial to only grep on the text.warc.gz file and not the originally rec-xxx.warc.gz file

Please find attached one try; (The archive result is always the same)

And finally the docker start command:
docker run -d --name ONB_Btrix_validate_insta_profile_20240328105141 -e NODE_OPTIONS="--max-old-space-size=32768" -p 9438:9438 -p 17412:17412  -v /home/netarchive/browsertrix/crawls/:/crawls/ webrecorder/browsertrix-crawler:1.0.2 crawl --screencastPort 9438 --seedFile /crawls/config/validate_insta_profile_seeds.txt  --profile /crawls/profiles/insta.tar.gz --scopeType prefix --depth 0 --extraHops 0 --workers 1 --healthCheckPort 17412 --limit 2 --sizeLimit 20971520 --timeLimit 300 --delay 15 --waitUntil networkidle0  --saveState always   --behaviorTimeout 10 --pageLoadTimeout 10  --text to-warc --logging stats,info --warcInfo ONB_CRAWL_validate_insta_profile_Depth_0_20240328105141 --userAgentSuffix +ONB_Bot_Btrix_1.0.2, webarchiv@onb.ac.at --crawlId id_ONB_CRAWL_validate_insta_profile_Depth_0_20240328105141 --collection validate_insta_profile_20240328105141

[validate_insta_profile_20240328105141.zip](https://github.com/webrecorder/browsertrix-crawler/files/14787576/validate_insta_profile_20240328105141.zip)

**Comment by gitreich** [comment]
retestet the exact same command with 
Version 1.0.3:
same result as above
Version 0.12.4
Working as expected

**Comment by ikreymer** [comment]
This was caused by the page load finishing too quickly, for some reason, this is now happening with Instagram.
To work around it, we have a new flag `--postLoadDelay`, eg. `--postLoadDelay 5` which you can use with Instagram, at least until we find out a better approach. This is now available on main / 1.1.0-beta.3 release.
