### ISSUE TITLE
Add optional fields to warcinfo that can identify who created the warc

### ISSUE THREAD

**Issue by karenhanson** [webrecorder/browsertrix-crawler#53]
The warcinfo metadata does not currently include properties that could identify which institution generated the WARC file. Fields such as `operator`, `ip`, and `hostname` would be helpful additions. These could be enabled/defined via the new YAML configuration file (https://github.com/webrecorder/browsertrix-crawler/issues/13).

**Comment by ikreymer** [comment]
Supported via #60, will be in 0.4.0-beta.3 release
