### ISSUE TITLE
`.warc` output, always write the warcinfo record ? 

### ISSUE THREAD

**Issue by dbuenzli** [webrecorder/browsertrix-crawler#553]
I noticed that the warcinfo record is not written in the files that that are in `collections/*/archive/*.warc.gz`. It only gets written in the combined archive written when `--combineWARC` is specified.

Is there any reason not to write it in every `collection/*/archive/*.warc.gz` file ? That way those can simply be combined at will by `cat`ing them (or not if we want to keep the files smaller). Rather than having to rely on the `--combineWARC` option. If I [understand well](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warcinfo) there's no issue with multiple `warcinfo`s, it simply applies to all subsequent records.

Also not sure it matters much but I noticed that the record is written with version `1.0` while the rest is written with version 1.1 (and I'm not sure that `format:` field matters much, it's written in all the records :-).

```
WARC/1.0
WARC-Filename: example.warc.gz
WARC-Date: 2024-04-18T21:49:24Z
WARC-Type: warcinfo
WARC-Record-ID: <urn:uuid:26769025-1e40-4b40-8ba9-99214b637fe4>
Content-Type: application/warc-fields
Content-Length: 90

software: Browsertrix-Crawler 1.0.4 (with warcio.js 2.2.1)
format: WARC File Format 1.0


WARC/1.1
WARC-Page-ID: 1e929081-aeaf-4814-bb55-54ef27b1a27c
WARC-Resource-Type: document
```

**Comment by ikreymer** [comment]
> I noticed that the warcinfo record is not written in the files that that are in `collections/*/archive/*.warc.gz`. It only gets written in the combined archive written when `--combineWARC` is specified.
> 
> Is there any reason not to write it in every `collection/*/archive/*.warc.gz` file ? That way those can simply be combined at will by `cat`ing them (or not if we want to keep the files smaller). Rather than having to rely on the `--combineWARC` option. If I [understand well](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warcinfo) there's no issue with multiple `warcinfo`s, it simply applies to all subsequent records.

There isn't a particularly good reason, other than historically they were created in different places, but that's no longer the case - have a PR open and will likely land adding warcinfo to all WARCs in 1.1.1


> Also not sure it matters much but I noticed that the record is written with version `1.0` while the rest is written with version 1.1 (and I'm not sure that `format:` field matters much, it's written in all the records :-).

yep, this is definitely confusing, was fixed for the crawler 1.1.0 release (changing all warcinfo records to 1.1)

**Comment by dbuenzli** [comment]
Thank you!

**Comment by Alseenrodelap** [comment]
The record-header is of all the warc files with the current version of Browsertrix is still/again: WARC/1.0.
