### ISSUE TITLE
Port 9222 can't be used for Screencast

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#558]
Please add to the docs that screencast (or healthcheck) on Port 9222 is not possible, because it is the ChromeDevTools Listening Port.

Starting a crawl like this:
docker run -p 9222:9222 -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler:1.0.4 crawl  --screencastPort 9222 --url https://netpreserve.org/ --generateWACZ --collection netpreserve-port-fails

or

docker run -p 9222:9222 -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler:1.0.4 crawl --healthCheckPort 9222 --url https://netpreserve.org/ --generateWACZ --collection netpreserve-port-fails

Error in both cases:
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:9222
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at new WSTransport (file:///app/dist/util/screencaster.js:30:25)
    at Crawler.initScreenCaster (file:///app/dist/crawler.js:224:25)
    at Crawler.crawl (file:///app/dist/crawler.js:792:34)
    at async Crawler.run (file:///app/dist/crawler.js:316:13)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 9222
}

Node.js v20.11.1

**Comment by ikreymer** [comment]
Is there a particular reason you need to use port 9222 for something other than chrome debug protocol?
You can run screencast and healthcheck on any different port, and then still map it to 9222 on the host machine, eg. `-p 9222:9037 ... --screencastPort 9037`

**Comment by gitreich** [comment]
No, I also don't think any code changes are necessary
In my case i have a random port usuage and check if the port is available on the localhost, but i was not aware of ports in the docker already used;
But I think it is good to notice this fact in the docs
