### ISSUE TITLE
--useSiteMap options is not working anymore

### ISSUE THREAD

**Issue by benoit74** [webrecorder/browsertrix-crawler#597]
It looks like `--useSiteMap` is not anymore working. 

When I set to use a sitemap with `crawl --sitemap`, the sitemap logic is triggered, but not when I `crawl --useSiteMap`. If I'm not mistaken, both are supposed to work.

Tested on 1.2.0-beta.0, but probably dated from waaaayyyyyy before that ^^

I'm not an expert in the arg parsing library and I'm not sure what the "alias" stuff means, not sure I can really help.

**Comment by ikreymer** [comment]
The flag is actually `--useSitemap` not `--useSiteMap` - not sure if it is possible to make it case-insensitive in yargs. It looks like it does add `--use-sitemap` as well, but not `--usesitemap`

**Comment by benoit74** [comment]
Oh, sorry about that, don't know this was case sensitive.
