### ISSUE TITLE
Revisit WARC-Resource-Type or add a new header

### ISSUE THREAD

**Issue by benoit74** [webrecorder/browsertrix-crawler#630]
This is a follow-up to https://github.com/webrecorder/browsertrix-crawler/issues/451. In this issue, we (Kiwix) had asked to have information about the initiator of the request in a WARC header to differentiate xhr/fetch from other requests.

This finally proved to not be needed, at least not for now in our warc2zim use case.

On the contrary, we realized it was very useful to detect which kind of document of given entry is representing, and how we should rewrite it (or not). Without this information we relied only on the HTTP response `Content-Type` header but some servers are lying, e.g. Cloudflare seems to regularly return `text/html` for `woff2` fonts.

Having a reliable source of information about which type of resource we are dealing with is very important for a static rewriting software like war2zim.

For now `WARC-Resource-Type` contains [Chrome Debug Protocol (CDP) resource type](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-ResourceType). Unfortunately, this contains some "catch-all" types like `xhr` or `fetch`. For now, we are hence combining information from the `WARC-Resource-Type` and the `Content-Type` header. This is working quite well, but it is a bit uncomfortable with all these "catch-all" values, and the fact that a lying server could still trick us.

I wonder if switching to the [Request.destination](https://developer.mozilla.org/en-US/docs/Web/API/Request/destination) would solve this problem. Would it be easy to implement a test on this (e.g. in a branch, I don't mind to test unofficial build made on my machine), where we could compare the result of the two sources of information?

Note that [webRequest.resourceType](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType) does not seems to be a fit, we have too few information, e.g. we do not have a distinction between JSON and JS `script`.

**Comment by ikreymer** [comment]
> I wonder if switching to the [Request.destination](https://developer.mozilla.org/en-US/docs/Web/API/Request/destination) would solve this problem. Would it be easy to implement a test on this (e.g. in a branch, I don't mind to test unofficial build made on my machine), where we could compare the result of the two sources of information?

We don't have a way to access `Request.destination` per se, but Chrome/Brave does set the [Sec-Fetch-Dest header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Dest) which is equivalent. In my experience, this is fairly comparable to the resourceType (i'm sure one is derived from the other). From what I've seen, it's not always set, there's still going to be catch-all `Sec-Fetch-Dest: empty` values. You can look at existing WARCs from the crawler and compare this field to the WARC-Resource-Type.

> For now `WARC-Resource-Type` contains [Chrome Debug Protocol (CDP) resource type](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-ResourceType). Unfortunately, this contains some "catch-all" types like `xhr` or `fetch`. For now, we are hence combining information from the `WARC-Resource-Type` and the `Content-Type` header. This is working quite well, but it is a bit uncomfortable with all these "catch-all" values, and the fact that a lying server could still trick us.

We've actually done this as well for the QA system, and will probably iterate on it further. I think some heuristic combining resource type, content-type and filename from URL will still be needed. What we have so far is here:
https://github.com/webrecorder/browsertrix/blob/b7631d1b91e264345fb27e8ec765f1029e08b0c8/frontend/src/pages/org/archived-item-qa/archived-item-qa.ts#L1240 and goal is to display useful categories to the user (and not things like xhr/fetch)

It's in the Browsertrix app frontend UI, but perhaps will make sense to factor out into a separate library at some point, or if you have something similar, might be good to try to standardize.

**Comment by benoit74** [comment]
Thank you! I experimented a bit with `set-fetch-dest` header and I confirm it is a promising source of information, but as you've seen it is quite often not set, defaulting to the `empty` value. So clearly not a magic solution, sadly.

I like the idea of combining your heuristics with ours (which is at https://github.com/openzim/warc2zim/blob/cbd431bde1b7c6725ccf1c67721cb39f83a6eb7c/src/warc2zim/content_rewriting/generic.py#L154-L182). This will be a bit tricky because you are quite "lax" (e.g. you consider it is worth trying to rewrite as HTML if "html" is present in the content type), probably because the UI then ignore any error which might occur if it wasn't really HTML, while we are quite strict because we wanna be sure it is HTML, and we stop on first error encountered (something detected as HTML must be rewritten, period). The classic "false positive" vs "false negative" balance.

**Comment by wumpus** [comment]
Here's how Common Crawl does it, we find a lot of wrong content types and their cause changes fairly rapidly over time. So we detect it and record both the claimed and detected content-type.

https://commoncrawl.github.io/cc-crawl-statistics/plots/mimetypes

**Comment by ikreymer** [comment]
Closing this as there isn't much to do here at this time. Will likely iterate on heuristics combining the mime type, resourceType and possible automated detection in other tools.
