### ISSUE TITLE
"Login form could not be found"

### ISSUE THREAD

**Issue by Azmodeszer** [webrecorder/browsertrix-crawler#637]
What is the proper syntax, if any, for specifying the login field names in the YAML config file?

This is the command I'm running
```
sudo docker run -v $PWD/crawls/profiles:/crawls/profiles -it webrecorder/browsertrix-crawler create-login-profile --headless --url "<URL>" --automated
```
After entering the credentials, I get
```
{"timestamp":"2024-07-09T09:40:39.787Z","logLevel":"debug","context":"browser","message":"Target Filter","details":{"url":"","type":"tab","attach":true}}
{"timestamp":"2024-07-09T09:40:39.797Z","logLevel":"debug","context":"browser","message":"Target Filter","details":{"url":"about:blank?_browsertrix5ovm89w1q7l","type":"page","attach":true}}
{"timestamp":"2024-07-09T09:40:39.826Z","logLevel":"info","context":"general","message":"Loading page: <URL>","details":{}}
{"timestamp":"2024-07-09T09:40:40.134Z","logLevel":"debug","context":"general","message":"Looking for username and password entry fields on page...","details":{}}
{"timestamp":"2024-07-09T09:41:10.147Z","logLevel":"debug","context":"general","message":"Login form could not be found","details":{}}
```

The login URL is correct, as are the credentials.

OS: Debian 12

**Comment by tw4l** [comment]
Hi @Azmodeszer, the `--automated` mode for browser profile creation doesn't at this time support passing login field names. It looks for the following:

```
try {
    u = await page.waitForSelector(
      "//input[contains(@name, 'user') or contains(@name, 'email')]",
    );
    p = await page.waitForSelector(
      "//input[contains(@name, 'pass') and @type='password']",
    );
  } ...
```

If this doesn't match what's on the page, your best bet is to use the default interactive mode and to manually log in via the resulting interactive browser session.

**Comment by Azmodeszer** [comment]
Alright, thanks. I'll try that.

**Comment by Azmodeszer** [comment]
@tw4l Alright, that works, but it raises the issue of me having to interactively renew the profile for each crawl? I'm trying to use Browsertrix for creating a regular offline copy of an internal site for a disaster case (httrack isn't behaving, so I'm trying alternatives). The crawl is supposed to run as a cron job on a regular basis. How can I create a persistent login profile?

**Comment by tw4l** [comment]
@Azmodeszer Yeah, you've hit the nail on the head in terms of what the issue is - because we're just storing cookies, they eventually expire, so you might have to create a profile each time to be sure.

If you have development capacity, we'd be happy to review a PR to pass in custom selectors for the automated login fields. Otherwise I can put it on my todo list but it might take a while as we have some competing priorities at the moment.

**Comment by tw4l** [comment]
No worries, I'm going to keep the issue open for now cause this will make a nice improvement when I can get to it.

**Comment by tw4l** [comment]
If you can provide a sample site with different login field names (e.g. the site you're trying to archive), I'd appreciate the test case!

**Comment by Azmodeszer** [comment]
The site I want to crawl is a NetBox instance, so the login page is essentially the same as the one for their public demo instance: view-source:https://demo.netbox.dev/login/?next=/

**Comment by tw4l** [comment]
@Azmodeszer my pleasure! We're actually starting a periodic "cleanup sprint" today so I was able to knock out a solution for this pretty quickly in this PR: https://github.com/webrecorder/browsertrix-crawler/pull/638

If you have the capacity to test it to ensure it works for you, I'd be grateful :)
