### ISSUE TITLE
'create profile' should accept cookies from Facebook

### ISSUE THREAD

**Issue by kauka-1** [webrecorder/browsertrix-crawler#64]
Automatic script 'create profile' manages to login into Facebook with username and password, 
but it doesn't click the 'Accept All' cookies button.

You can see that when using debugScreenshot option.

When browsing in replayweb, 'accept cookies' window pops up on every page.

![LOGINKUVA](https://user-images.githubusercontent.com/71389212/123617172-a6d4b900-d80f-11eb-92d5-afe0c069ec2b.jpg)

**Comment by ikreymer** [comment]
Starting with 0.4.0, Browsertrix Crawler now includes support for an 'interactive' profile creation mode where you can log-in to sites and then interact with an embedded browser. You can use this to click on any 'Accept Cookies' messages on any site.

Many sites have such 'accept cookies' dialog boxes and detecting them automatically can be tricky (though ideally can be done). The interactive solution should work well for now.

See: https://github.com/webrecorder/browsertrix-crawler#interactive-profile-creation for more info on this feature.
