### ISSUE TITLE
Crawler keeps signing out(?)

### ISSUE THREAD

**Issue by Azmodeszer** [webrecorder/browsertrix-crawler#642]
Thanks again for the quick [recent fix](https://github.com/webrecorder/browsertrix-crawler/pull/638) regarding selectors for creating profiles. This has solved my problem with automatically logging into the site I want to crawl. However, now it seems as if the crawler keeps logging out again shortly after starting the container?

I am attempting to create an offline copy of a NetBox instance, so the login screen and URL structure are basically the same as this public demo instance: https://demo.netbox.dev/ (I am actually crawling a local instance, but I'll use this URL as a placeholder in the commands provided below) 

I first create the profile
````
docker run -v $PWD/crawls/profiles:/crawls/profiles -it webrecorder/browsertrix-crawler create-login-profile --url "https://demo.netbox.dev/" --headless --automated --cookieDays 7
````

which works fine with the provided credentials.

Then I start the crawl
````
docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --profile /crawls/profiles/profile.tar.gz --url https://demo.netbox.dev/ --generateWACZ --collection test-with-profile --headless
````

And this chugs along nicely, until pretty quickly the URLs in the log all switch to `https://demo.netbox.dev/login/?next=/<some subpath>`, i.e. it appears the crawler logs out again(?) and all it's doing is capture the same login page over and over. Indeed, that is what I see when I open the resulting WARC file with Webrecorder: One instance of the (logged in) main page and everything else is a `/login/?next=/` URL with some subpath, naturally all displaying the same login page.

Or did the login simply expire?

**Comment by ikreymer** [comment]
It could be the login has expired, another possibility is the crawler visits the logout page. It looks like it could be a link? If so, be sure to exclude 'logout' from being crawled with --exclude option

**Comment by Azmodeszer** [comment]
Welp, talk about an obvious fix. Yeah, adding the logout link as an exclusion fixed it. Thanks.
