### ISSUE TITLE
der-postillon.com: crawler considers that scrolling is not necessary while it seems mandatory

### ISSUE THREAD

**Issue by benoit74** [webrecorder/browsertrix-crawler#647]
Command used:

```
docker run -v $PWD/output:/output --name crawlme --rm  webrecorder/browsertrix-crawler:1.2.4 crawl --failOnFailedSeed --behaviors "autoplay,autofetch,autoscroll" --url "https://www.der-postillon.com/"  --mobileDevice "Pixel 2" --cwd /output --combineWARC --depth 0 
```

Main issue is that most news preview images are missing in the WARC. Most because the two first images are present (but needs a fuzzy rule, easy, done in https://github.com/openzim/warc2zim/pull/349/commits/118cfca7c981fbc8b41775d95590b22c6998b7b6 for warc2zim):
- https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjlN4LY6kFVwL8-rinDWp3kJp1TowOVD8vq8TP8nl3Lf1sI-hx0DE1GQA1jw7DT7XvK3FjghzJ17_1pvyXyDBAV0vtigJRnFCNfMxnndBnN3NYoXUvKQQsQ7JTGXOSajdo0mNQIv8wss_AxPBMrR4-Dd_EEacV7ZMS3m_IL2dz0WsbbKn7FD7ntsfOe0JUq/s600-rw/tickerzugtier2.jpg=w487-h220-p-k-no-nu  is present (but needs to be rewritten since on desktop the website tries to fetch https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjlN4LY6kFVwL8-rinDWp3kJp1TowOVD8vq8TP8nl3Lf1sI-hx0DE1GQA1jw7DT7XvK3FjghzJ17_1pvyXyDBAV0vtigJRnFCNfMxnndBnN3NYoXUvKQQsQ7JTGXOSajdo0mNQIv8wss_AxPBMrR4-Dd_EEacV7ZMS3m_IL2dz0WsbbKn7FD7ntsfOe0JUq/s600-rw/tickerzugtier2.jpg=w253-h165-p-k-no-nu)
- https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiT_Lr7bDM81R7aST5GM2Otr3SWETWUW_qoDeW978BvNHVbTRV-Vxxrxez98a1-wMqpQSjXYGkHYO_KmrbJ2DfJ4cxRNo0e2voNrKXorfxGgfhjCx0GIEOl5B8gnfl-x34TU-WUvKtlpB9k/s600-rw/Gulaschquiz.jpg=w169-h110-p-k-no-nu is present (needs to be rewritten as well)
- https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEir_n_ruq2HCEqBeUPRnvFsbNxy2nkgPTAMcdDQMovyGRJwwSr1WXwyM1lhvml-DIxu8rmfeOoXUBsKjucjE8dYiUOlB7c1hSfR79B6efZBFcc-_ZYd2eBLoXxmQwqqpv9rYqEeIAaXTukoi3li8vgZbQ9c-AnblOfI4Ksq_Ap6A8BdDyEWc-iDCkrBDjY/s600-rw/Duden-dasselbe-das-Gleiche-3.jpg=w253-h165-p-k-no-nu  is missing and not available in another resolution (we only have the squared "preview" at https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEir_n_ruq2HCEqBeUPRnvFsbNxy2nkgPTAMcdDQMovyGRJwwSr1WXwyM1lhvml-DIxu8rmfeOoXUBsKjucjE8dYiUOlB7c1hSfR79B6efZBFcc-_ZYd2eBLoXxmQwqqpv9rYqEeIAaXTukoi3li8vgZbQ9c-AnblOfI4Ksq_Ap6A8BdDyEWc-iDCkrBDjY/w72-h72-p-k-no-nu/Duden-dasselbe-das-Gleiche-3.jpg)

Problem seems to be that the crawler considers that page is not responsive to scrolling, while obviously it is needed.

```
{"timestamp":"2024-07-17T09:02:31.009Z","logLevel":"info","context":"behavior","message":"Run Script Started","details":{"frameUrl":"chrome-error://chromewebdata/","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.019Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.020Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.022Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.022Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.024Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.024Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.025Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.025Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.027Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.027Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.035Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.035Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"done!","page":"https://www.der-postillon.com/","workerid":0}}
{"timestamp":"2024-07-17T09:02:31.517Z","logLevel":"info","context":"behaviorScript","message":"Behavior log","details":{"state":{"segments":1},"msg":"Skipping autoscroll, page seems to not be responsive to scrolling events","page":"https://www.der-postillon.com/","workerid":0}}
```

Adding a `--waitUntil load,networkidle0` does not help.

Any idea? Thank you!

**Comment by ikreymer** [comment]
A quick look at this site shows that there's a cookie popup that is not blocked by Brave, and requires clicking for the page to be scrollable. This can be fixed with a browser profile. With a profile, it does indeed scroll all the way and the page images do replay.

**Comment by benoit74** [comment]
Arf, thank you, didn't thought that the cookie popup might be the issue.
