### ISSUE TITLE
Don't log behavior-related messages if no behaviors are set

### ISSUE THREAD

**Issue by tw4l** [webrecorder/browsertrix-crawler#651]
Related to https://github.com/webrecorder/browsertrix/pull/1963#pullrequestreview-2195469333

When the behaviors argument is set to an empty list (meaning no behaviors), we should not log behavior-related messages such as `"Running behaviors"`, `"Run Script Started"`, and `"Waiting for behaviors to finish"` among others.

Their presence is confusing noise if behaviors are disabled.

**Comment by ikreymer** [comment]
Yeah, I think we should make sure we disable the execution of browsertrix-behaviors altogether if all behaviors are disabled, that may not be the case..
