### ISSUE TITLE
ETA computation

### ISSUE THREAD

**Issue by wsdookadr** [webrecorder/browsertrix-crawler#660]
I wrote a small prototype to compute how much time is left for an ongoing crawl. The only pre-requisite for it on a regular Linux system is [ripgrep](https://github.com/BurntSushi/ripgrep).
In my case depth=0 and scopeType=page and I feed an urlFile with a list of urls. This is the intended use-case.

In the formula below:

```
a - epoch for the first crawled page
b - epoch for the latest crawled page
d - pages completed
t - total pages
```

For me this is useful because I can find out how much time is left.

I'm sharing this and have two questions:
* can an ETA computation be added to browsertrix
* is it possible (and how) to estimate a crawl with depth > 0

```bash
#!/bin/bash
LOG=$(find crawls/ -name "crawl*.log" -printf "%T@ %p\n" | sort -n | tail -1 | awk '{print $2}')
TS1=$(rg "Starting page" $LOG | head -1 | jq -c -r '.timestamp' | perl -pne 's/\.\d+Z//g' | xargs -I{} date -d"{}" +%s)
TS2=$(rg "Starting page" $LOG | tail -1 | jq -c -r '.timestamp' | perl -pne 's/\.\d+Z//g' | xargs -I{} date -d"{}" +%s)
DONE=$(tail -100 $LOG | jq -c -r 'select(.context | contains("crawlStatus")) | .details.crawled' | tail -1)
TOTAL=$(tail     -100 $LOG | jq -c -r 'select(.context | contains("crawlStatus")) | .details.total' | tail -1)

<<'COMMENTS'
b-a ..   d
?   .. t-d

(b-a)*(t-d)/d
COMMENTS

perl -e '
($a,$b,$d,$t) = @ARGV;
$e = int((($b-$a)*($t-$d))/$d);
$eh= sprintf("%.2f", ($e/3600));
$ed= sprintf("%.2f", ($e/86400));
print "$ed days left\n";
print "$eh hours left\n";
' $TS1 $TS2 $DONE $TOTAL
```

Example output:
```
1.11 days left
26.75 hours left
```

**Comment by ikreymer** [comment]
If we were to add anything like this, it might be in the Browsertrix app where we can track repeated crawls over time, but its not a priority. Not sure there is much we can do here for now, so will close this issue.
