### ISSUE TITLE
A suggestion for making WACZ and WARC-requests

### ISSUE THREAD

**Issue by hamoudak** [webrecorder/browsertrix-crawler#663]
I would like to be wacz-requests section as there is already zim-requests ;because I've seen many people not have the ability (for instance, system-requirements or enough space etc.) or knowledge for crawling a website with browsertrix . manual-archiving with archiveweb.page is good and easily handled but it will produce many links for archiving a website. so I think this idea will help many.

**Comment by ikreymer** [comment]
We have a service that we offer, https://browsertrix.com/, where you can sign-up and run crawls via a UI. The crawls are run via Browsertrix Crawler. Unfortunately, we don't have the resources to offer WACZ files of sites on-demand, like the Zimit service does.  One idea, perhaps, is for Zimit could offer WACZ files alongside ZIM as part of the same crawl - that's a question for @benoit74 @rgaudin and others.

**Comment by hamoudak** [comment]
thank you for clearing this up; I do know the website for a long time but all I see is  [log in] and the premium offers. will it be free or something.

**Comment by tw4l** [comment]
> thank you for clearing this up; I do know the website for a long time but all I see is [log in] and the premium offers. will it be free or something.

Our hosted service is and will remain a paid service, but the software is FOSS and it is possible to self-host if you're comfortable with Kubernetes: https://github.com/webrecorder/browsertrix. Probably more than you want to do given the requirements about system limitations in the issue description, but it is an option.

**Comment by benoit74** [comment]
> One idea, perhaps, is for Zimit could offer WACZ files alongside ZIM as part of the same crawl

Definitely not something "light" to implement, we suppose we are dealing with ZIM files in multiple places ^^ Pretty sure we will probably never make it unless there is something stronger than someone wishing to have this feature
