### ISSUE TITLE
Invalid URLs in seeds file

### ISSUE THREAD

**Issue by kauka-1** [webrecorder/browsertrix-crawler#67]
Hi,
crawl doesn't start if there is even one 'Invalid URL' in seeds file, for example 

yle.fi 
instead of 
https://yle.fi

Crawler should jump over invalid URLs, log them in errors and continue with valid URLs?

**Comment by ikreymer** [comment]
Hm, thinking the error message should be improved to log the invalid URLs, but not sure if should continue?
Seems like its probably an error and user would want to fix the invalid URLs before proceeding.

**Comment by kauka-1** [comment]
Yes, a bit more information in log files is probably enough.
- - - 
However, if a set of 100 seeds contains 5 errors, operator has to start the crawl 5 times to fix one URL at a time.
If Browsertrix continues with valid seeds (while logging possible errors) main crawl needs just one run. Operator can check errors later and make a new run with 5 fixed URLs.

(Heritrix continues a crawl and logs seed errors in reports/seeds-report.txt for later checks.)
