### ISSUE TITLE
[Bug]: Crawl Configuration Inconsistency: Max Depth and Include Any Linked Page

### ISSUE THREAD

**Issue by mona-ul** [webrecorder/browsertrix-crawler#693]
### Browsertrix Version

v1.11.7-7a61568

### What did you expect to happen? What happened instead?

I have a question about the settings Max Depth and Include Any Linked Page. 
I think there might me an error in the implementation of the rules. 

As I understand it, 
- the max depth apply to pages that are in scope. That means, pages would be cut, due to max depth. It limits the pages, that are in scope. "Limits how many hops away the crawler can visit while staying within the Start URL Scope."
- The one hop out adds all pages, that are linked by pages in scope. 
"If checked, the crawler will visit pages one link away outside of Start URL Scope."

Right now, the crawler from browsertix is not behaving as I would think.

### Reproduction instructions

**Example:**
I've created an example page for illustration: https://monaulrich.online/scopetest/start/

**Crawl Config "Scope Domain & Subdomain / Max Depth 1"**
Here the Crawler includes what I would expect. 
The start url and the 4 linked page, that have the same domain/subdomain are archived. 
These pages are in scope.
![example_structure_in_scope](https://github.com/user-attachments/assets/a76f7ec0-100b-445e-8fac-ef4d34f6828e)

**Crawl Config "Scope Domain & Subdomain / Max Depth 1 / Include Any Linked Page: True"**
I would expect, that all the pages, that are in scope based on the settings Scope Domain & Subdomain and Max Depth: 1, are checked for any linked pages. But only the pages 1 depth away from the start URL are included. 

Browsertrix Output:
![example_structure_scope_linked_pages_actual](https://github.com/user-attachments/assets/496be778-f2fc-4a75-b094-e00638f8d4de)

What I would expect:
![example_structure_scope_linked_pages_expected](https://github.com/user-attachments/assets/c2a1c387-c140-4104-b0dd-2fb3b4fa3525)

I am not sure, if i misunderstand the settings, or if there is an inconsistency in the implementation.
Thanks in advance.

**Comment by tw4l** [comment]
I would agree with fixing it as-is! I also shared a same mental model of what should happen that corresponds to @mona-ul 's expected (but not actual) result. My leaning would be to treat this like a bug and patch it without any additional flags. Perhaps we can also be more explicit in the documentation about what's expected - the visual aids here really helped clarify!

**Comment by Shrinks99** [comment]
+1 for fix as is! @mona-ul thanks for the clear explination and diagrams!

**Comment by mona-ul** [comment]
Thank you for your fast reply and clarification.
