### ISSUE TITLE
BUG: Create Browser Profile --headless can't render at viewport

### ISSUE THREAD

**Issue by gitreich** [webrecorder/browsertrix-crawler#696]
Since Version 1.3.0 (Also 1.3.1) the generating of browser profiles with the parameter --headless fails because the page is not rendering in the browser anymore ( CDP is not even show, screen is white, only createProfile button is available, see screenshot) 
If I start the same command without --headless it is working;

Command was:
**docker run -p 6080:6080 -p 9222:9222 -p 9223:9223 -v $PWD/crawls/profiles:/crawls/profiles/ -it webrecorder/browsertrix-crawler:1.3.1 create-login-profile  --filename "/crawls/profiles/new_twitter.tar.gz" --url "http://x.com/" --headless 
**

![Bildschirmfoto vom 2024-10-04 12-44-34](https://github.com/user-attachments/assets/9215e176-5f0f-42e4-959e-70f29efc49dd)

**Comment by ikreymer** [comment]
Sorry, I'm not able to repro this:
<img width="1423" alt="Screenshot 2024-10-04 at 3 27 17 PM" src="https://github.com/user-attachments/assets/48ad655b-e0b4-4472-b201-97506a102b66">

The headless mode uses the devtools that comes with the browser. It used to only work in Chromium-based browsers, but actually now does work in Firefox and Safari, but maybe not as well. If you're using an older browser, it may not render correctly.
It looks like there may be some error logs as well, would be helpful to include them. So far, tried it in a bunch of browsers and no issues.

**Comment by gitreich** [comment]
Hi thanks for your fast replay
You are right it is connected to the Chrome Version! My Version is 128.0.6613.119 (Offizieller Build) (64-Bit)
But the same viewport was working in
Brave [Version 1.69.168 Chromium: 128.0.6613.138 (Offizieller Build) (64-Bit)](https://brave.com/latest/)
and
firefox 130.0.1 (64-Bit)
I will update Chrome and tell you if it's working (I guess yes)

**Comment by gitreich** [comment]
Not even the Browser was but uBlock Origin was the reason: it showed one blocked rescource

/metrics/metrics$from=~chrome-devtools-frontend.appspot.com|~docs.datadoghq.com|~github.com|~source.dot.net|~spatineo.com

was the blocked rescource
