### ISSUE TITLE
Manually create a profile.tar.gz

### ISSUE THREAD

**Issue by djhmateer** [webrecorder/browsertrix-crawler#731]
Is it possible to manually create a profile.tar.gz as in 

```bash
docker run -p 6080:6080 -p 9223:9223 -v $PWD/crawls/profiles:/crawls/profiles/ -it webrecorder/browsertrix-crawler create-login-profile --url "https://facebook.com/"
```

I started looking in here:
https://github.com/webrecorder/browsertrix-crawler/blob/fb8ed18f82fb321a404d1d43b414e89299808835/src/create-login-profile.ts#L1

`C:\Users\djhma\AppData\Local\Google\Chrome\User Data` - I tried tar.gz'ing this directory but it didn't seem to work.

![image](https://github.com/user-attachments/assets/10160e62-c45a-443b-8be9-b43b14afa7fb)

I've posted here too https://forum.webrecorder.net/t/manually-create-and-use-a-profile-tar-gz/702

Facebook is not happy with the docker profile.tar.gz creation process.

**Comment by tw4l** [comment]
Hi @djhmateer, part of the issue may be that Browsertrix Crawler uses Brave Browser, which has a similar browser profile data structure to Chrome in that they are both Chromium-based but I would guess diverge at some points. I'm also not sure if the user profiles differ by operating system - the current [browsertrix-browser-base Dockerfile](https://github.com/webrecorder/browsertrix-browser-base/blob/main/Dockerfile) is based on Ubuntu 24.

My guess would be that a manually saved and tarred/gzipped user data directory from a Brave browser installation would work but I haven't tested this myself, not sure if it'd have to be from the same OS as well.

**Comment by djhmateer** [comment]
Hi @tw4l - thank  you so much for the reply. Will test and report back.

**Comment by djhmateer** [comment]
Brave 1.78.102 works.

```bash
sudo apt install brave-browser=1.78.102
```

The current version gives me this error:

```bash
{"timestamp":"2025-07-19T08:05:21.433Z","logLevel":"info","context":"general","message":"With Browser Profile","details":{"url":"/crawls/profile-5c2f8160.tar.gz"}}
{"timestamp":"2025-07-19T08:05:22.451Z","logLevel":"error","context":"general","message":"Crawl failed","details":{"type":"exception","message":"Protocol error (Target.setDiscoverTargets): Target closed","stack":"TargetCloseError: Protocol error (Target.setDiscoverTargets): Target closed\n    at CallbackRegistry.clear (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:77:36)\n    at #onClose (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:175:25)\n    at WebSocket.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:42:30)\n    at callListener (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)\n    at WebSocket.onClose (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:220:9)\n    at WebSocket.emit (node:events:524:28)\n    at WebSocket.emitClose (/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:272:10)\n    at Socket.socketOnClose (/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1341:15)\n    at Socket.emit (node:events:524:28)\n    at TCP.<anonymous> (node:net:343:12)"}}
```
