### ISSUE TITLE
profile.tar.gz not found

### ISSUE THREAD

**Issue by billsargent** [webrecorder/browsertrix-crawler#79]
This is the error I get when trying to use a profile I created. I can see the file. its there. 

`
Error: Command failed: tar xvfz /home/bill/crawls/profiles/profile.tar.gz
tar (child): /home/bill/crawls/profiles/profile.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

`

This is my commandline

`docker run -p 9037:9037 -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl --profile /home/bill/crawls/profiles/profile.tar.gz --url https://www.dummyhiddenurl.com/ --screencastPort 9037 --behaviors autoscroll,autoplay,autofetch,siteSpecific --scopeType host --workers 10 --headless --newContext window`

Here is the full error:

`tar (child): /home/bill/crawls/profiles/profile.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
node:child_process:903
    throw err;
    ^

Error: Command failed: tar xvfz /home/bill/crawls/profiles/profile.tar.gz
tar (child): /home/bill/crawls/profiles/profile.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at module.exports.loadProfile (/app/util/browser.js:10:19)
    at new Crawler (/app/crawler.js:59:23)
    at Object.<anonymous> (/app/main.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  status: 2,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(218) [Uint8Array] [
      116,  97, 114,  32,  40,  99, 104, 105, 108, 100,  41,  58,
       32,  47, 104, 111, 109, 101,  47,  98, 105, 108, 108,  47,
       99, 114,  97, 119, 108, 115,  47, 112, 114, 111, 102, 105,
      108, 101, 115,  47, 112, 114, 111, 102, 105, 108, 101,  46,
      116,  97, 114,  46, 103, 122,  58,  32,  67,  97, 110, 110,
      111, 116,  32, 111, 112, 101, 110,  58,  32,  78, 111,  32,
      115, 117,  99, 104,  32, 102, 105, 108, 101,  32, 111, 114,
       32, 100, 105, 114, 101,  99, 116, 111, 114, 121,  10, 116,
       97, 114,  32,  40,
      ... 118 more items
    ]
  ],
  pid: 14,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(218) [Uint8Array] [
    116,  97, 114,  32,  40,  99, 104, 105, 108, 100,  41,  58,
     32,  47, 104, 111, 109, 101,  47,  98, 105, 108, 108,  47,
     99, 114,  97, 119, 108, 115,  47, 112, 114, 111, 102, 105,
    108, 101, 115,  47, 112, 114, 111, 102, 105, 108, 101,  46,
    116,  97, 114,  46, 103, 122,  58,  32,  67,  97, 110, 110,
    111, 116,  32, 111, 112, 101, 110,  58,  32,  78, 111,  32,
    115, 117,  99, 104,  32, 102, 105, 108, 101,  32, 111, 114,
     32, 100, 105, 114, 101,  99, 116, 111, 114, 121,  10, 116,
     97, 114,  32,  40,
    ... 118 more items
  ]
}
`

Here's the file:
```

root@bill-HP-Pavilion-15-Notebook-PC:/home/bill/crawls/profiles# ls -lh
total 9,0M
-rw-r--r-- 1 root root 8,9M aug  9 12:45 profile.tar.gz

```

Also I am logged in as root... I know. bad practice. But its just a junk test machine. what am I doing wrong?

**Comment by ikreymer** [comment]
The profile is also being loaded inside the Docker container, so it needs to have a path relative to the container.
Since the local crawls dir is being mapped to `/crawls` and the profile is in there, the path can just be `/crawls/profiles/profile.tar.gz`

The following should work:

```
docker run -p 9037:9037 -v $PWD/crawls:/crawls/ webrecorder/browsertrix-crawler crawl --profile /crawls/profiles/profile.tar.gz --url https://www.dummyhiddenurl.com/ --screencastPort 9037 --behaviors autoscroll,autoplay,autofetch,siteSpecific --scopeType host --workers 10 --headless --newContext window
```

**Comment by billsargent** [comment]
That was it! :) I swear I tried that too. Ah well, it was pretty late when I was messing around with it. :) Thanks for your help.
