### ISSUE TITLE
Stopping and resuming the crawler

### ISSUE THREAD

**Issue by justiceloxley787** [webrecorder/browsertrix-crawler#85]
Is there a way to stop the crawler and resume it later so I can do things like resuming the crawl in case of failure, changing configuration, or crawling the site only in idle hours?

**Comment by ikreymer** [comment]
This is now possible in latest 0.5.0 beta and from the build on main. See https://github.com/webrecorder/browsertrix-crawler#interrupting-and-restarting-the-crawl for initial documentation.
