### ISSUE TITLE
One or more workers are not working.

### ISSUE THREAD

**Issue by rmfkdehd** [webrecorder/browsertrix-crawler#93]
Below is my command...
workers is 6 and it keeps coming out as 1.
My cpu has 6 cores and 12 threads. The ram is 64gb, no problem.....

`docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --url https://example.com/ --generateWACZ --text --collection test --scopeType any -workers 6`

**Comment by ikreymer** [comment]
It looks like you have a typo, missing dash, it should be ´--workers´ not ´-workers´

**Comment by rmfkdehd** [comment]
Thanks... I should have checked more closely...
